### ISSUE TITLE
Error: chequebook init: transaction underpriced

### ISSUE THREAD

**Issue by totodata** [ethersphere/bee#1783] opened 2021-05-20 01:43 UTC
bee start error:

INFO[2021-05-20T09:12:46+08:00] using swarm network address through clef: 87ff04da3fefec02b9621a0f5871cef72deed9bed18552bfb269f1cc51e056ae
INFO[2021-05-20T09:12:46+08:00] swarm public key 024b932524c84bec320330b7f974ae7259eefb1263abca05096741716da3b98a7e
DEBU[2021-05-20T09:12:46+08:00] using existing libp2p key
DEBU[2021-05-20T09:12:46+08:00] using existing pss key
INFO[2021-05-20T09:12:46+08:00] pss public key 03279adc36325fe44e3de3842280ad96557524503d8add06cb8f22ebfdf7435cb2
INFO[2021-05-20T09:12:46+08:00] using ethereum address 585b793fe260a0c6e9707c114847f4fc726aa23f
INFO[2021-05-20T09:12:46+08:00] debug api address: [::]:1635
INFO[2021-05-20T09:12:48+08:00] using default factory address for chain id 5: f0277caffea72734853b834afc9892461ea18474
INFO[2021-05-20T09:12:49+08:00] waiting for chequebook deployment in transaction 7ff22373db7f1a0aafeb168330c9848e13d11e0eab312ccbe7fdc03c24c366fd
INFO[2021-05-20T09:12:49+08:00] deployed chequebook at address 36053b7dc47631ea836b0aa7eecc369f18faa135
INFO[2021-05-20T09:12:49+08:00] depositing 100000000000000000 token into new chequebook
TRAC[2021-05-20T09:12:50+08:00] sending transaction 06a1e022b77c1c074d0ae8c565288a484ac573e319a7a72db8f58950a141aee3 with nonce 1
Error: chequebook init: transaction underpriced

address:
https://goerli.etherscan.io/address/0x585b793fe260a0c6e9707c114847f4fc726aa23f

**Comment by pontali** [comment] 2021-06-03 17:59
I also encountered the same problem, is there a solution? For example, setting the price of gas...

**Comment by acud** [comment] 2021-08-10 23:05
@ralph-pichler is this still a possible issue now that we're on xdai?

**Comment by acud** [comment] 2021-08-12 14:43
closing this since we don't have enough information to reproduce this. if the problem still persists please open a new issue and try to provide as much information as possible

**Closed by acud** 2021-08-12 14:43 UTC
Labels: bug, issue
