### ISSUE TITLE
"could not store file" publishing bzz file

### ISSUE THREAD

**Issue by tmm360** [ethersphere/bee#3101] opened 2022-07-19 22:07 UTC
### Context
Running 1.6.2 on Docker

### Summary
Tried to POST a new file on `/bzz`, I receive this message.
```
{"message":"could not store file","code":500}
```

### Expected behavior
File should be published.

### Steps to reproduce
Don't know how to reproduce, but I can say that I'm also seeing this issue #3090

**Comment by acud** [comment] 2022-07-25 11:21
most probably related to https://github.com/ethersphere/bee/issues/3039, but more logs in `debug` would be needed in order to corroborate this.

**Comment by tmm360** [comment] 2022-07-25 19:04
I'm verifying this also with 1.7.0, and this are related logs:

```
time="2022-07-25T18:57:42Z" level=error msg="bzz upload file: file store, file \"\""
time="2022-07-25T18:57:42Z" level=info msg="api access" duration=0.043139277 host=gatenode.etherna.network ip=10.0.8.74 method=POST proto=HTTP/1.1 referrer="https://etherna.io/" size=71 status=500 uri=/bzz user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36" x-forwarded-for="185.159.157.44, 151.139.95.96, 151.139.87.49, 10.0.0.37, 10.0.8.74" x-real-ip=10.0.0.37
```

**Comment by acud** [comment] 2022-07-26 06:10
is there anything above the `error` log level message? what we're looking for is above those messages.

**Comment by agazso** [comment] 2022-07-26 08:29
> is there anything above the `error` log level message? what we're looking for is above those messages.

I see this also on the gateway nodes, maybe it's better to check to logs on those.

**Comment by tmm360** [comment] 2022-07-26 12:13
> is there anything above the `error` log level message? what we're looking for is above those messages.

unfortunately no, but I will try to run in trace mode.

**Comment by tmm360** [comment] 2022-07-26 22:18
[beeLogs.txt](https://github.com/ethersphere/bee/files/9193660/beeLogs.txt)
Here trace logs, with a single POST on bzz, failing at line 2918

**Comment by ldeffenb** [comment] 2022-07-26 22:21
2 lines before that, this doesn't look right to my eyes:
"bzz upload file: file store, file \"\": put upload: same slot remove: get value: leveldb: not found"

**Comment by ldeffenb** [comment] 2022-07-26 22:24
Also note that this was only 1 minute after the node was started.  The pusher won't be active yet, but I haven't seen early uploads cause anything about slot removals in my logs.

It is best to wait until your node's warmup period has completed before attempting to upload files, especially if you expect them to be pushed into the swarm and retrievable via other nodes.   The default warmup period is 5 minutes unless you have an old configuration .yaml file that may specify 20 minutes.

**Comment by tmm360** [comment] 2022-07-26 22:27
> Also note that this was only 1 minute after the node was started. The pusher won't be active yet, but I haven't seen early uploads cause anything about slot removals in my logs.
> 
> It is best to wait until your node's warmup period has completed before attempting to upload files, especially if you expect them to be pushed into the swarm and retrievable via other nodes. The default warmup period is 5 minutes unless you have an old configuration .yaml file that may specify 20 minutes.

This is not relevant, because the issue appears also with node running for days. I've started in trace mode and uploaded shortly because I wanted to keep minimum the logs. Anyway, the file should be accepted, and pushed when ready

**Comment by tmm360** [comment] 2022-08-03 14:00
Would be possible to prioritize this? It is a blocking issue for us.

**Comment by agazso** [comment] 2022-08-04 08:14
Did you by any chance nuke the database ever? Trying to reduce the possibilities what may have cause this.

**Comment by tmm360** [comment] 2022-08-04 14:24
> Did you by any chance nuke the database ever? Trying to reduce the possibilities what may have cause this.

I can try, and I will. Anyway we have to 2 out of 2 nodes with this problem, and is probable that will happen again.

**Comment by agazso** [comment] 2022-08-04 14:29
Maybe it was not clear, but I was not suggesting to nuke the database. It was just a clarifying question if you did in the past, because we see this behavior with nodes that were nuked before, but that may be related some inconsistency caused by the nuking itself.

Thanks for answering anyhow! 😄

**Comment by tmm360** [comment] 2022-08-04 14:34
Oh, sorry! Yes I did. If I remember I had to because of data leak issue.

But if you say that a clean node doesn't have this issue, I could full rebuild them.

**Comment by aloknerurkar** [comment] 2022-08-04 14:38
Also, are you using the same stamps for the upload?

It would help if you use completely new batches. This happens if you upload a lot of data or similar data with the same stamps.

**Comment by tmm360** [comment] 2022-08-04 14:42
Yes, I confirm, I'm reusing same postage for similar data. We are going to change this, but currently it is how application works. Thanks for advice!

**Comment by aloknerurkar** [comment] 2022-08-08 10:42
@tmm360

So this is a duplicate of #3039. Closing this now.

**Closed by aloknerurkar** 2022-08-08 10:42 UTC
Labels: bug, issue
