### ISSUE TITLE
External signer integration tests

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#679] opened 2020-09-08 08:46 UTC
Integration testing `clef` with `bee` should achieve the following:
- [ ] start a 1 or 2 node network, with clef as signer backend, and somehow induce the nodes to create messages and sign them. Signatures should be valid. It is not clear whether they should be signing cheques or should the signatures be induced by a debug api endpoint.

Integration testing new `clef` configuration with `bee` requires some changes to be made to the way we deploy `bee`. Namely:
- a `clef` container (including init phase) should accompany every `bee` container (`bee` would use that `clef` node to sign messages, single owner chunks and transactions)
- a `geth` backend should ideally exist per cluster. ideally this should be an isolated self-bootstrapped blockchain, so that we avoid time and resources associated with using the real blockchain as a backend
- current `beekeeper` tests could potentially stay as-is, without the dependency on `clef`, since current model for external signing is `opt-in`.

**Comment by Eknir** [comment] 2020-10-20 14:06
@vandot add additional comments.

**Comment by vandot** [comment] 2020-10-28 09:42
Whole implementation is done.
Clef is implemented as a sidecar container https://github.com/ethersphere/helm/pull/50
There is a possibility to start geth with prefunded clef keys.
Clef is still not enabled on infra tests because there is some bug in clef itself, @ralph-pichler knows more about it and he submitted bug report to clef repo

**Comment by Eknir** [comment] 2020-10-30 14:45
Thanks for the info @vandot , I put this issue on the icebox. @ralph-pichler , could you please provide additional information on the bug and the report you made? Thanks!

**Comment by ralph-pichler** [comment] 2020-11-01 22:36
I think there was some misunderstanding here. It is not a bug in clef but there was an issue in bee which only happened during the clef tests (a combined effect of the lower payment threshold and the latency added by clef signing) which lead to a deadlock due to peers holding each others accounting lock. Unfortunately the solution to this caused another issue which still causes problems with the clef test but also outside of it if a remote node is used. (hence we might revert the previous fix and have to solve it differently, see issue #892).

**Comment by Eknir** [comment] 2020-11-03 08:21
Thanks for the information Ralph! Closing this issue, as #892 is tracking it now.

**Closed by Eknir** 2020-11-03 08:21 UTC
Labels: Epic
