### ISSUE TITLE
fix: bee dev has a lot of errors in the output

### ISSUE THREAD

**Issue by significance** [ethersphere/bee#4046] opened 2023-05-04 08:06 UTC
other than this, it is awesome 😍 

can we clean it up please?

i bought a stamp and uploaded some chunks, but it seems to panic a lot even when running normally.

<img width="2087" alt="Screenshot 2023-05-04 at 09 02 47" src="https://user-images.githubusercontent.com/130104/236145694-e055243c-d77b-4839-9eee-b78fcd08416e.png">

**Comment by Cafe137** [comment] 2023-05-22 16:32
The culprit seems to be the staking endpoint.

```
"time"="2023-05-22 18:31:04.732943" "level"="error" "logger"="node" "msg"="http: panic serving [::1]:57559: runtime error: invalid memory address or nil pointer dereference\ngoroutine 979 [running]:\nnet/http.(*conn).serve.func1()\n\tnet/http/server.go:1854 +0xb0\npanic({0x102068cc0, 0x102b90050})\n\truntime/panic.go:890 +0x258\ngithub.com/ethersphere/bee/pkg/storageincentives/staking/mock.(*stakingContractMock).GetStake(0x140000ef3b0?, {0x102251200?, 0x14001536a20?})\n\tgithub.com/ethersphere/bee/pkg/storageincentives/staking/mock/contract.go:28 +0x24\ngithub.com/ethersphere/bee/pkg/api.(*Service).getStakedAmountHandler(0x14000088380, {0x10224e800, 0x14000159c70}, 0x1400158b800)\n\tgithub.com/ethersphere/bee/pkg/api/staking.go:88 +0xa0\nnet/http.HandlerFunc.ServeHTTP(0x10205ad80?, {0x10224e800?, 0x14000159c70?}, 0x3?)\n\tnet/http/server.go:2122 +0x38\ngithub.com/ethersphere/bee/pkg/jsonhttp.HandleMethods(0x1400208b560, {0x101b2bf78, 0x2b}, {0x101b13141, 0x1f}, {0x10224e800?, 0x14000159c70}, 0x1400158b800)\n\tgithub.com/ethersphere/bee/pkg/jsonhttp/handlers.go:25 +0xf4\ngithub.com/ethersphere/bee/pkg/jsonhttp.MethodHandler.ServeHTTP(0x102251200?, {0x10224e800?, 0x14000159c70?}, 0x102e56280?)\n\tgithub.com/ethersphere/bee/pkg/jsonhttp/handlers.go:17 +0x50\ngithub.com/ethersphere/bee/pkg/api.(*Service).gasConfigMiddleware.func1.1({0x10224e800, 0x14000159c70}, 0x1400158b700)\n\tgithub.com/ethersphere/bee/pkg/api/api.go:632 +0x204\nnet/http.HandlerFunc.ServeHTTP(0x100?, {0x10224e800?, 0x14000159c70?}, 0x0?)\n\tnet/http/server.go:2122 +0x38\ngithub.com/ethersphere/bee/pkg/api.(*Service).stakingAccessHandler.func1({0x10224e800, 0x14000159c70}, 0x14002051400?)\n\tgithub.com/ethersphere/bee/pkg/api/staking.go:29 +0xa4\nnet/http.HandlerFunc.ServeHTTP(0x1400158b600?, {0x10224e800?, 0x14000159c70?}, 0x100cd1afc?)\n\tnet/http/server.go:2122 +0x38\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0x14000166300, {0x10224e800, 0x14000159c70}, 0x1400158b500)\n\tgithub.com/gorilla/mux@v1.8.0/mux.go:210 +0x19c\nresenje.org/web.NewSetHeadersHandler.func1({0x10224e800, 0x14000159c70}, 0x14000d82901?)\n\tresenje.org/web@v0.4.3/set_headers.go:28 +0x178\nnet/http.HandlerFunc.ServeHTTP(0x102150bc0?, {0x10224e800?, 0x14000159c70?}, 0x16?)\n\tnet/http/server.go:2122 +0x38\ngithub.com/ethersphere/bee/pkg/api.(*Service).corsHandler.func1({0x10224e800, 0x14000159c70}, 0x1400158b500)\n\tgithub.com/ethersphere/bee/pkg/api/api.go:654 +0x3e0\nnet/http.HandlerFunc.ServeHTTP(0x1400051d7a0?, {0x10224e800?, 0x14000159c70?}, 0x4?)\n\tnet/http/server.go:2122 +0x38\ngithub.com/gorilla/handlers.CompressHandlerLevel.func1({0x10224dfc0, 0x14000d82920}, 0x1400158b500)\n\tgithub.com/gorilla/handlers@v1.4.2/compress.go:148 +0x8a8\nnet/http.HandlerFunc.ServeHTTP(0x14001f8fa08?, {0x10224dfc0?, 0x14000d82920?}, 0x10109b284?)\n\tnet/http/server.go:2122 +0x38\ngithub.com/ethersphere/bee/pkg/log/httpaccess.NewHTTPAccessLogHandler.func1.1({0x10224ffa0?, 0x140024fd7a0?}, 0x1400158b500)\n\tgithub.com/ethersphere/bee/pkg/log/httpaccess/http_access.go:41 +0xf8\nnet/http.HandlerFunc.ServeHTTP(0x10?, {0x10224ffa0?, 0x140024fd7a0?}, 0xf1f0?)\n\tnet/http/server.go:2122 +0x38\nnet/http.serverHandler.ServeHTTP({0x140015367e0?}, {0x10224ffa0, 0x140024fd7a0}, 0x1400158b500)\n\tnet/http/server.go:2936 +0x2d8\nnet/http.(*conn).serve(0x1400075aa20, {0x102251200, 0x14000e7c0f0})\n\tnet/http/server.go:1995 +0x560\ncreated by net/http.(*Server).Serve\n\tnet/http/server.go:3089 +0x520\n"
```

**Comment by mrekucci** [comment] 2023-09-13 11:38
Duplicate of #4022

**Closed by mrekucci** 2023-09-13 11:38 UTC
Labels: issue, needs-triaging, user-experience
