### ISSUE TITLE
redistributionstate , an error is returned,  Curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by HAILANG1234321** [ethersphere/bee#3866] opened 2023-03-06 07:55 UTC
⚠️ Support requests in an issue-format will be closed immediately. For support, go to Swarm's [Discord](https://discord.gg/XGNBEKktkD).

### Context

This is an error I extracted from the log. Other api queries have data. An error is reported when the API curl of redistribution is used. The error log is as follows:  level"="error" "logger"="node" "msg"="http: panic serving 127.0.0.1:53394: runtime error: invalid memory address or nil pointer dereference\ngoroutine 567898 [running]:\nnet/http.(conn).serve.func1()\n\tnet/http/server.go:1802 +0xb9\npanic({0x1221840, 0x24b6d20})\n\truntime/panic.go:1047 +0x266\ngithub.com/ethersphere/bee/pkg/storageincentives.(Agent).Status(...)\n\tgithub.com/ethersphere/bee/pkg/storageincentives/agent.go:473\ngithub.com/ethersphere/bee/pkg/api.(*Service).redistributionStatusHandler(0xc00012b180, {0x18eb0a0, 0xc005d3d540}, 0x0)\n\tgithub.com/ethersphere/bee/pkg/api/redistribution.go:30 +0xc7\nnet/http.HandlerFunc.ServeHTTP(0x1214020, {0x18eb0a0, 0xc005d3d540}

**Comment by mrekucci** [comment] 2023-03-06 10:43
Duplicate of #3810

**Closed by mrekucci** 2023-03-06 10:43 UTC
Labels: issue, needs-triaging
