### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by veqtor** [ethersphere/bee#1472] opened 2021-03-23 08:32 UTC
#### Summary
Bee crashed

#### Steps to reproduce
Run bee for a while, don't know much more

#### Actual behavior
```

panic: runtime error: slice bounds out of range [:16] with capacity 0

goroutine 66738288 [running]:
github.com/ethersphere/bee/pkg/localstore.New.func4(0xc003a364e0, 0x20, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/ethersphere/bee/pkg/localstore/localstore.go:233 +0xd1
github.com/ethersphere/bee/pkg/shed.Index.Get(0xc001cb6a90, 0xc000b87962, 0x1, 0x1, 0xc001ec28c0, 0xc000b89a10, 0x1703f40, 0x1703f48, 0xc003a364e0, 0x20, ...)
        github.com/ethersphere/bee/pkg/shed/index.go:154 +0x2aa
github.com/ethersphere/bee/pkg/localstore.(*DB).get(0xc0000ea600, 0x0, 0xc003a364e0, 0x20, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/ethersphere/bee/pkg/localstore/mode_get.go:61 +0x1f8
github.com/ethersphere/bee/pkg/localstore.(*DB).Get(0xc0000ea600, 0x1863680, 0xc009260f30, 0x0, 0xc003a364e0, 0x20, 0x20, 0x0, 0x0, 0x0, ...)
        github.com/ethersphere/bee/pkg/localstore/mode_get.go:46 +0x194
github.com/ethersphere/bee/pkg/retrieval.(*Service).handler(0xc001d26600, 0x1863680, 0xc009260f30, 0xc00d578040, 0x20, 0x20, 0x186a940, 0xc031dd9c20, 0x0, 0x0)
        github.com/ethersphere/bee/pkg/retrieval/retrieval.go:337 +0x554
github.com/ethersphere/bee/pkg/p2p/libp2p.(*Service).AddProtocol.func1(0x1876640, 0xc031dd9c00)
        github.com/ethersphere/bee/pkg/p2p/libp2p/libp2p.go:372 +0x876
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandlerMatch.func1(0xc00bf57fe0, 0x20, 0x7f93001e4310, 0xc031dd9c00, 0x1, 0x0)
        github.com/libp2p/go-libp2p@v0.13.0/p2p/host/basic/basic_host.go:580 +0x9f
created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
        github.com/libp2p/go-libp2p@v0.13.0/p2p/host/basic/basic_host.go:416 +0x613


```

**Comment by Eknir** [comment] 2021-03-23 08:35
duplicate of https://github.com/ethersphere/bee/issues/1340, fixed by https://github.com/ethersphere/bee/pull/1426

**Closed by Eknir** 2021-03-23 08:35 UTC
Labels: bug, issue
