### ISSUE TITLE
Sometimes unreasonable memory consumption

### ISSUE THREAD

**Issue by d10r** [ethersphere/bee#1319] opened 2021-02-23 10:53 UTC
I have several bee instances running, using a build based on https://github.com/ethersphere/bee/commit/62c576e74389ddf88c6c16488ab992dc4b9aa38a (specifically, with https://github.com/ethersphere/bee/pull/1282 already included).  
While memory consumption seems to have considerably improved compared to v0.5.0 (where all bee processes seem to slowly crawl to higher and higher memory allocation all the time), I currently have one process which spiked to >16G resident memory (more than double of that virtual memory) in less than 12 hours and another one which went to ~1,4G RES / 27G VIRT.  
The other bee processes remain in a range of few 100 MB RES.
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                
  45263 bee       30  10   38.9g  18.1g   9808 S 106.6  28.9 375:27.05 bee114                                                                                                                 
  39512 bee       30  10   27.9g   1.4g   8844 S  14.3   2.3 402:36.97 bee101                                                                                                                 
  43449 bee       30  10 4711728 335536   9140 S  10.6   0.5 201:39.09 bee206                                                                                                                 
  39519 bee       30  10 1011664 310980   9896 S  34.2   0.5 167:23.21 bee102                                                                                                                 
    415 root      19  -1  532348 303520 302068 S   8.3   0.5  49:18.66 systemd-journal                                                                                                        
  43479 bee       30  10 1972428 214256   9484 S   7.0   0.3 176:33.06 bee209                                                                                                                 
  43378 bee       30  10 1698172 203304   9976 S  15.0   0.3 197:03.33 bee105 
...
```
(no, I'm not running >100 bees on that machine, it's just a numbering scheme - 1xx use disk1, 2xx use disk2)

I checked open sockets and files, but nothing abnormal there when comparing "misbehaving" to "behaving" bees.  
Configuration wise they are equal, only different port numbers.  
One difference I notice - which may or may not be relevant: bee114 (the excessive one) has the smallest DB size at the moment:
```
du -smx /data1/bees/*
...
16880   /data1/bees/111
10909   /data1/bees/112
15054   /data1/bees/113
9813    /data1/bees/114
...
```
The difference is not huge (they all range btw. ~10G and ~20G at the moment), but still...

Since the process is still running (for now - I fear at some point it will exhaust all memory), I could provide further insights if somebody can give me a hint what to look for.

clef is not used here.

PS: that's how overall memory allocation changed over time:
<img width="748" alt="image" src="https://user-images.githubusercontent.com/5479136/108833134-aeb7ee80-75cc-11eb-8841-0c27fa30762b.png">
I guess the upshot around 9AM was bee114 getting too excited about something.

**Comment by d10r** [comment] 2021-02-23 21:55
~12 hours later it looks like this: 
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                                                       
  45263 bee       30  10   38.9g   7.2g   8648 S  15.9  11.5 613:52.01 bee114                                                                                                                                                                                                                        
  39512 bee       30  10   27.9g   1.2g   8632 S   6.3   1.8 481:49.65 bee101                                                                                                                                                                                                                        
  43419 bee       30  10 7725484 451520   9564 S  14.3   0.7 349:52.20 bee109                                                                                                                                                                                                                        
    415 root      19  -1  494996 312864 311960 S   5.3   0.5  96:01.32 systemd-journal                                                                                                                                                                                                               
  43449 bee       30  10 4712240 305440   6248 S   8.3   0.5 311:13.86 bee206                                                                                                                                                                                                                        
 119494 bee       30  10 3277160 271972   8752 S  15.0   0.4 169:22.06 bee216
```
So, VIRT has remained the same, but RES has come done considerably for bee114.

**Comment by d10r** [comment] 2021-02-23 22:02
This I find interesting:
![image](https://user-images.githubusercontent.com/5479136/108913791-c1611080-762a-11eb-9b4b-790838f7650e.png)
I don't really know, but would guess that the drop occured where the graph shows the drop for "committed memory". I didn't start or stop anything at that time, looks to me like the system reacting on mounting memory pressure - see swap activity going up around the same time. Maybe the garbage collector was pressed to do something.

**Comment by d10r** [comment] 2021-03-01 12:56
I just observed such an "incident" in realtime - a spike from <1 GB RES to >2GB RES in many small increments in less than a minute.  
It was while the log got a lot of entries like this:
```
Mar 01 13:54:09 nody bee103[1110537]: time="2021-03-01T13:54:09+01:00" level=error msg="pushsync: new stream for peer 74733b46fcd92b4f9766bace70f223f9ed201393333f02f27a2fae9c06c018b0: send headers: read message: context deadline exceeded"
Mar 01 13:54:09 nody bee103[1110537]: time="2021-03-01T13:54:09+01:00" level=error msg="pushsync: new stream for peer 74733b46fcd92b4f9766bace70f223f9ed201393333f02f27a2fae9c06c018b0: send headers: read message: context deadline exceeded"
Mar 01 13:54:10 nody bee103[1110537]: time="2021-03-01T13:54:10+01:00" level=error msg="pushsync: new stream for peer 74733b46fcd92b4f9766bace70f223f9ed201393333f02f27a2fae9c06c018b0: send headers: read message: context deadline exceeded"
```

so maybe there's a hint there.

**Comment by Eknir** [comment] 2021-03-03 21:04
On Discord: 
> One only throws evel=debug msg="could not handle protocol pushsync/1.0.0: stream pushsync: peer 395c0aa9be3d8dff863dbd3120e338f37257138b3489e104d50609374f40a6dc: error: send receipt to peer 395c0aa9be3d8dff863dbd3120e338f37257138b3489e104d50609374f40a6dc: stream reset"
and this fills RAM up to OutOfMemory exception

**Comment by Eknir** [comment] 2021-03-23 08:06
Hi @d10r , we got several improvements, currently in master that would address this. We will release shortly. We would greatly appreciate if you could have a look and validate if the situation improves. Closing this issue for the time being as this is a very general issue and not directly actionable.

**Closed by Eknir** 2021-03-23 08:06 UTC
Labels: bug, issue

**Comment by d10r** [comment] 2021-03-24 13:11
thx for the update.
I updated to 0.5.4-08c92e9 and restarted the nodes about 18h ago.  
The issue at hand doesn't seem to have gone away:

![image](https://user-images.githubusercontent.com/5479136/112315516-8219f400-8caa-11eb-9f97-ed8b12600595.png)

If you have any idea how I could give more useful feedback, let me know.
I'm not familiar with Go, but could probably manage to dig a bit deeper anyway, e.g. by attaching a profiler, if pointed to the right docs and given specific enough instructions about what to look for.  
I'm also reachable on the Swarm Mattermost for clarifications.

**Comment by d10r** [comment] 2021-03-25 11:10
Here's the output of http://localhost:1635/debug/pprof/allocs?debug=1 of this instance:
```
     PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND 
3396077 bee       30  10   18.6g   1.3g  12972 R  32.3   2.0 818:34.71 bee115
```

[bee_115_allocs.txt](https://github.com/ethersphere/bee/files/6204170/bee_115_allocs.txt)

**Comment by ldeffenb** [comment] 2021-03-25 11:49
Is this running on a magnetic disk?  Or is the disk I/O otherwise saturated, possibly by too many nodes running?  I've seen similar (without knowing how to look up the allocation details) on nodes running on machines whose disk writing is falling behind the network's ability to deliver data, especially with pullsync and lots of peers.

**Comment by d10r** [comment] 2021-03-25 12:10
the additional profiling data requested in Mattermost:
[pprof.bee.goroutine.001.pb.gz](https://github.com/ethersphere/bee/files/6204514/pprof.bee.goroutine.001.pb.gz)
[pprof.bee.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz](https://github.com/ethersphere/bee/files/6204515/pprof.bee.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz)

@ldeffenb it's running on NVMe disks. However it may well be possible that it's saturated.  
As suggested, I'm running multiple nodes with the default storage size and there's > 1TB storage available.  
I thought since it's fast storage and overall a performant machine, that should be possible.

If not, what's the recommended way to provide that amount of storage to Swarm? Increase the capacity per node instead?

**Comment by ldeffenb** [comment] 2021-03-25 13:39
This is the only published guidance on storage space: https://docs.ethswarm.org/docs/advanced/large-node-operators

It's all new software, so we're experimenting.  If you have a way to check the underlying host disk accesses (I use "sudo atop" along with munin performance monitoring), I suspect you'll find that the disks are 100% busy.  That causes I/O backlogs into the bee nodes which will cause increased memory consumption as it tries to write (and read) more data than the disks can handle.

The same thing can happen with even a single node if the data is on magnetic media.

Free disk space (> 1TB available) is not a measure of disk subsystem performance, but you probably already know that.

And there's an old maxim that software will grow to and beyond the limits of any hardware you can throw at it.  "fast storage" and "performant machine" can still be overrun with too much load.  And right now, bee nodes are not light resource users.  Hopefully it will improve, but the approach seems to be "functionality first", "performance later".

**Comment by acud** [comment] 2021-04-03 05:59
> the additional profiling data requested in Mattermost:
> [pprof.bee.goroutine.001.pb.gz](https://github.com/ethersphere/bee/files/6204514/pprof.bee.goroutine.001.pb.gz)
> [pprof.bee.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz](https://github.com/ethersphere/bee/files/6204515/pprof.bee.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz)
> 
> @ldeffenb it's running on NVMe disks. However it may well be possible that it's saturated.
> As suggested, I'm running multiple nodes with the default storage size and there's > 1TB storage available.
> I thought since it's fast storage and overall a performant machine with high bandwidth, that should be possible.
> 
> If not, what's the recommended way to provide that amount of storage to Swarm? Increase the capacity per node instead?

@d10r sorry for taking so long to reply. We've looked into the heap dumps you've provided but have not found anything particularly wrong there. The problem is that the go runtime just doesn't release the allocated memory back to the OS. For users that have a lot of RAM this issue is particularly visible, since the OS doesn't need to reclaim the memory anyway and can just keep on allocating. A nice test would be to have a different process that actually allocates a lot of active memory to run alongside the bee nodes in order to verify that the just stop allocating new memory.
In any case, this should be improved with go 1.16 if I'm not mistaken. We haven't upgraded yet, but hopefully before the next release is out.
