### ISSUE TITLE
error while checking pending transactions: header not found

### ISSUE THREAD

**Issue by RealLau** [ethersphere/bee#1919] opened 2021-05-30 07:45 UTC
#### Summary

Encountered a problem when starting bee in net goerli
`error while checking pending transactions: header not found`
#### Steps to reproduce

I'm a new comer of bee, when I starting bee in net goerli, I encountered an error:
```
error while checking pending transactions: header not found
```
and here is my config 
```json
password: some_password
swap-endpoint: https://goerli.infura.io/v3/some_endpoint
debug-api-enable: true
full-node: true
```
#### Expected behavior

Can this be ignored or fixed by some operations, if so, can someone tell me how?
#### Actual behavior

As the mentioned error above.

I run bee on ubuntu amd64, bee version(`0.6.1-79ad7f08`).

**Comment by wonliang** [comment] 2021-06-01 15:56
error while checking pending transactions: header not found

**Comment by wonliang** [comment] 2021-06-01 16:05
How did you solve it?

**Comment by RealLau** [comment] 2021-06-01 16:44
> How did you solve it?

still not resolved, just keep an eye on this.

**Comment by acud** [comment] 2021-08-12 14:57
Closing this as this is expected behavior and will be visible when using a load balanced ethereum backend (e.g. Infura). This is not really an error, since the backend will retry to fetch the data (this happens when you're getting a different ethereum backend from the load balancer)

**Closed by acud** 2021-08-12 14:57 UTC
Labels: bug, issue
