### ISSUE TITLE
LevelDB panics when running pushsync with race

### ISSUE THREAD

**Issue by jmozah** [ethersphere/bee#163] opened 2020-05-07 09:31 UTC
The following panic was found only once and seems to be in one of the libraries used by leveldb.
This is created as a placeholder to see of this occurs again. if this happens agin, we escalate it to leve;ldb issues.

```
fatal error: runtime: mcall called on m->g0 stack

runtime stack:
runtime: unexpected return pc for github.com/cespare/xxhash/v2.(*Digest).Sum64 called from 0xc0003a2698
stack: frame={sp:0xc0003a2600, fp:0xc0003a2678} stack=[0x27d54000,0x27f4fe80)

encoding/binary.littleEndian.Uint64(...)
        C:/Users/HP/sdk/go1.14.2/src/encoding/binary/binary.go:79
github.com/cespare/xxhash/v2.u64(...)
        C:/Users/HP/go/pkg/mod/github.com/cespare/xxhash/v2@v2.1.1/xxhash.go:212
github.com/cespare/xxhash/v2.(*Digest).Sum64(0x101, 0xc0003a2630)
        C:/Users/HP/go/pkg/mod/github.com/cespare/xxhash/v2@v2.1.1/xxhash.go:138 +0x2c1

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0002398c0, 0xc7f7a4, 0xb, 0xca0cb8, 0x1)
        C:/Users/HP/sdk/go1.14.2/src/testing/testing.go:1043 +0x6a0
testing.runTests.func1(0xc0002398c0)
        C:/Users/HP/sdk/go1.14.2/src/testing/testing.go:1284 +0xae
testing.tRunner(0xc0002398c0, 0xc0000b9d50)
        C:/Users/HP/sdk/go1.14.2/src/testing/testing.go:991 +0x1f3
testing.runTests(0xc000208420, 0x1169680, 0x2, 0x2, 0x0)
        C:/Users/HP/sdk/go1.14.2/src/testing/testing.go:1282 +0x52f
testing.(*M).Run(0xc00026c000, 0x0)
        C:/Users/HP/sdk/go1.14.2/src/testing/testing.go:1199 +0x307
main.main()
        _testmain.go:48 +0x22b

goroutine 16095 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc00060c8c0)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 16030 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0004ff180)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15360 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0012f4c40)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15494 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc00060d6c0)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15423 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0004ff340)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15794 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0004fe380)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15957 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc00060c000)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15581 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0000d9500)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15640 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0001728c0)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 16161 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc00057ea80)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15303 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0000d8540)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15540 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0012f4fc0)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15314 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc00060c1c0)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15777 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0012f4540)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15189 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0000d8000)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15548 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc00060d340)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15911 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0004fe8c0)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15719 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc00057e000)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15503 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc000172700)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15588 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0000d9180)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15276 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0000d8380)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15854 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc000172540)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15471 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc00060cfc0)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 16151 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc000172a80)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15490 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0000d8e00)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 14583 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc00060d180)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15247 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc00060ce00)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15941 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc00038a000)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 16261 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc000708000)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/util/buffer_pool.go:206 +0x1d2
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/util/buffer_pool.go:237 +0x2fb

goroutine 15979 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc00060c540)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15677 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0012f4000)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15919 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0004fea80)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15033 [runnable]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc00057fa40)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15705 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0000d9a40)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15567 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc00060d500)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 15930 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc00060c380)
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db_state.go:110 +0x29e
created by github.com/syndtr/goleveldb/leveldb.openDB
        C:/Users/HP/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20190923125748-758128399b1d/leveldb/db.go:149 +0x7ec

goroutine 16260 [GC assist wait]:
fatal error: unexpected signal during runtime execution
panic during panic
[signal 0xc0000005 code=0x0 addr=0xe8 pc=0x49af06]

runtime stack:
runtime: unexpected return pc for github.com/cespare/xxhash/v2.(*Digest).Sum64 called from 0xc0003a2698
stack: frame={sp:0xc0003a2600, fp:0xc0003a2678} stack=[0x27d54000,0x27f4fe80)

encoding/binary.littleEndian.Uint64(...)
        C:/Users/HP/sdk/go1.14.2/src/encoding/binary/binary.go:79
github.com/cespare/xxhash/v2.u64(...)
        C:/Users/HP/go/pkg/mod/github.com/cespare/xxhash/v2@v2.1.1/xxhash.go:212
github.com/cespare/xxhash/v2.(*Digest).Sum64(0x101, 0xc0003a2630)
        C:/Users/HP/go/pkg/mod/github.com/cespare/xxhash/v2@v2.1.1/xxhash.go:138 +0x2c1
FAIL    github.com/ethersphere/bee/pkg/pushsync 14.799s
FAIL
```

## Acceptance criterea
cd pkg/pushsync
go test -race  -count 1000 .

should not create this issue

**Comment by Eknir** [comment] 2020-07-14 12:25
Closing for now, cannot reproduce

**Closed by Eknir** 2020-07-14 12:25 UTC
Labels: bug
