### ISSUE TITLE
Panic when reuploading in dev mode

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#2448] opened 2021-08-25 13:49 UTC
#### Summary
I was trying the reupload functionality with a node in dev mode and Bee paniced.

#### Steps to reproduce
I started a node in dev mode (commit `tags/v1.1.0`, `80cdea196bcf0c5943af9f5638bfda242c2877ff`). 
The node was empty, I bought a postage stamp, uploaded some data, pinned it and then tried to reupload the data with swarm-cli. The equivalent curl command (printed by the swarm-cli `--curl` option) is:

```
curl -X PUT http://localhost:1633/stewardship/b2df49710b98d38a780a8fab76c23ef5b55884ebeeee6397817974be7892add9 -H "Accept: application/json, text/plain, */*" -H "Content-Type: application/x-www-form-urlencoded"
```
#### Expected behavior
The operation succeeds and the node returns 200.

#### Actual behavior

Node logs:
```
% ../bee/dist/bee dev

 (                      *        )  (           
 )\ )                 (  *    ( /(  )\ )        
(()/(   (    (   (    )\))(   )\())(()/(   (    
 /(_))  )\   )\  )\  ((_)()\ ((_)\  /(_))  )\   
(_))_  ((_) ((_)((_) (_()((_)  ((_)(_))_  ((_)  
 |   \ | __|\ \ / /  |  \/  | / _ \ |   \ | __| 
 | |) || _|  \ V /   | |\/| || (_) || |) || _|  
 |___/ |___|  \_/    |_|  |_| \___/ |___/ |___|                


Starting in development mode

INFO[2021-08-25T15:39:35+02:00] debug api address: [::]:1635                 
INFO[2021-08-25T15:39:35+02:00] database capacity: 1000 chunks (approximately 16.4GB) 
INFO[2021-08-25T15:39:35+02:00] api address: [::]:1633                       
INFO[2021-08-25T15:39:42+02:00] api access                                    duration=0.000221602 ip=127.0.0.1 method=GET proto=HTTP/1.1 size=21 status=200 uri=/pins user-agent=axios/0.21.1
INFO[2021-08-25T15:40:10+02:00] debug api access                              duration=0.0001849 ip=127.0.0.1 method=GET proto=HTTP/1.1 size=17 status=200 uri=/stamps user-agent=axios/0.21.1
INFO[2021-08-25T15:40:34+02:00] debug api access                              duration=0.000995133 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=80 status=201 uri=/stamps/1000000000/20 user-agent=axios/0.21.1
INFO[2021-08-25T15:40:39+02:00] debug api access                              duration=0.000137633 ip=127.0.0.1 method=GET proto=HTTP/1.1 size=249 status=200 uri=/stamps user-agent=axios/0.21.1
INFO[2021-08-25T15:40:41+02:00] debug api access                              duration=0.000108954 ip=127.0.0.1 method=GET proto=HTTP/1.1 size=249 status=200 uri=/stamps user-agent=axios/0.21.1
INFO[2021-08-25T15:40:43+02:00] debug api access                              duration=7.1333e-05 ip=127.0.0.1 method=GET proto=HTTP/1.1 size=249 status=200 uri=/stamps user-agent=axios/0.21.1
INFO[2021-08-25T15:40:47+02:00] debug api access                              duration=0.000115155 ip=127.0.0.1 method=GET proto=HTTP/1.1 size=249 status=200 uri=/stamps user-agent=axios/0.21.1
INFO[2021-08-25T15:40:52+02:00] debug api access                              duration=8.5892e-05 ip=127.0.0.1 method=GET proto=HTTP/1.1 size=249 status=200 uri=/stamps user-agent=axios/0.21.1
INFO[2021-08-25T15:40:53+02:00] api access                                    duration=0.296363956 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=82 status=201 uri=/bzz user-agent=axios/0.21.1
INFO[2021-08-25T15:40:53+02:00] debug api access                              duration=0.000110882 ip=127.0.0.1 method=GET proto=HTTP/1.1 size=238 status=200 uri=/stamps/9c0293059dd2596d0e6794afe8d21f69282f183abbbb55abd6966bbe200fb2ee user-agent=axios/0.21.1
INFO[2021-08-25T15:41:04+02:00] api access                                    duration=0.002640545 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=34 status=201 uri=/pins/b2df49710b98d38a780a8fab76c23ef5b55884ebeeee6397817974be7892add9 user-agent=axios/0.21.1
INFO[2021-08-25T15:41:22+02:00] api access                                    duration=0.000370296 ip=127.0.0.1 method=GET proto=HTTP/1.1 size=85 status=200 uri=/pins user-agent=axios/0.21.1
INFO[2021-08-25T15:41:35+02:00] api access                                    duration=0.000125907 ip=127.0.0.1 method=GET proto=HTTP/1.1 size=85 status=200 uri=/pins user-agent=axios/0.21.1
INFO[2021-08-25T15:41:35+02:00] api access                                    duration=0.00018812 ip=127.0.0.1 method=GET proto=HTTP/1.1 size=82 status=200 uri=/pins/b2df49710b98d38a780a8fab76c23ef5b55884ebeeee6397817974be7892add9 user-agent=axios/0.21.1
ERRO[2021-08-25T15:41:35+02:00] http: panic serving 127.0.0.1:63401: runtime error: invalid memory address or nil pointer dereference 
ERRO[2021-08-25T15:41:35+02:00] goroutine 22340 [running]:                   
ERRO[2021-08-25T15:41:35+02:00] net/http.(*conn).serve.func1(0xc000616820)   
ERRO[2021-08-25T15:41:35+02:00] 	net/http/server.go:1801 +0x147              
ERRO[2021-08-25T15:41:35+02:00] panic(0x20cd620, 0x2eff8a0)                  
ERRO[2021-08-25T15:41:35+02:00] 	runtime/panic.go:975 +0x47a                 
ERRO[2021-08-25T15:41:35+02:00] github.com/ethersphere/bee/pkg/api.(*server).stewardshipPutHandler(0xc000d1a160, 0x25fc9a0, 0xc001b3db20, 0xc00082b200) 
ERRO[2021-08-25T15:41:35+02:00] 	github.com/ethersphere/bee/pkg/api/stewardship.go:25 +0xfe 
ERRO[2021-08-25T15:41:35+02:00] net/http.HandlerFunc.ServeHTTP(0xc00061b180, 0x25fc9a0, 0xc001b3db20, 0xc00082b200) 
ERRO[2021-08-25T15:41:35+02:00] 	net/http/server.go:2042 +0x44               
ERRO[2021-08-25T15:41:35+02:00] github.com/ethersphere/bee/pkg/api.(*server).gatewayModeForbidEndpointHandler.func1(0x25fc9a0, 0xc001b3db20, 0xc00082b200) 
ERRO[2021-08-25T15:41:35+02:00] 	github.com/ethersphere/bee/pkg/api/router.go:222 +0x165 
ERRO[2021-08-25T15:41:35+02:00] net/http.HandlerFunc.ServeHTTP(0xc0005f2fa0, 0x25fc9a0, 0xc001b3db20, 0xc00082b200) 
ERRO[2021-08-25T15:41:35+02:00] 	net/http/server.go:2042 +0x44               
ERRO[2021-08-25T15:41:35+02:00] resenje.org/web.HandleMethods(0xc0002e5fb0, 0x22f81a4, 0x2b, 0x22df118, 0x1f, 0x25fc9a0, 0xc001b3db20, 0xc00082b200) 
ERRO[2021-08-25T15:41:35+02:00] 	resenje.org/web@v0.4.3/method.go:20 +0x5f6  
ERRO[2021-08-25T15:41:35+02:00] github.com/ethersphere/bee/pkg/jsonhttp.MethodHandler.ServeHTTP(0xc0002e5fb0, 0x25fc9a0, 0xc001b3db20, 0xc00082b200) 
ERRO[2021-08-25T15:41:35+02:00] 	github.com/ethersphere/bee/pkg/jsonhttp/handlers.go:16 +0x76 
ERRO[2021-08-25T15:41:35+02:00] github.com/gorilla/mux.(*Router).ServeHTTP(0xc000140780, 0x25fc9a0, 0xc001b3db20, 0xc00082b000) 
ERRO[2021-08-25T15:41:35+02:00] 	github.com/gorilla/mux@v1.7.4/mux.go:210 +0xd3 
ERRO[2021-08-25T15:41:35+02:00] github.com/ethersphere/bee/pkg/api.(*server).gatewayModeForbidHeadersHandler.func1(0x25fc9a0, 0xc001b3db20, 0xc00082b000) 
ERRO[2021-08-25T15:41:35+02:00] 	github.com/ethersphere/bee/pkg/api/router.go:240 +0x64 
ERRO[2021-08-25T15:41:35+02:00] net/http.HandlerFunc.ServeHTTP(0xc0005f3160, 0x25fc9a0, 0xc001b3db20, 0xc00082b000) 
ERRO[2021-08-25T15:41:35+02:00] 	net/http/server.go:2042 +0x44               
ERRO[2021-08-25T15:41:35+02:00] github.com/ethersphere/bee/pkg/api.(*server).setupRouting.func5.1(0x25fc9a0, 0xc001b3db20, 0xc00082b000) 
ERRO[2021-08-25T15:41:35+02:00] 	github.com/ethersphere/bee/pkg/api/router.go:207 +0xd2 
ERRO[2021-08-25T15:41:35+02:00] net/http.HandlerFunc.ServeHTTP(0xc0005f3180, 0x25fc9a0, 0xc001b3db20, 0xc00082b000) 
ERRO[2021-08-25T15:41:35+02:00] 	net/http/server.go:2042 +0x44               
ERRO[2021-08-25T15:41:35+02:00] github.com/ethersphere/bee/pkg/api.(*server).pageviewMetricsHandler.func1(0x25fc9a0, 0xc001b3db20, 0xc00082b000) 
ERRO[2021-08-25T15:41:35+02:00] 	github.com/ethersphere/bee/pkg/api/metrics.go:63 +0xb1 
ERRO[2021-08-25T15:41:35+02:00] net/http.HandlerFunc.ServeHTTP(0xc0005f31a0, 0x25fc9a0, 0xc001b3db20, 0xc00082b000) 
ERRO[2021-08-25T15:41:35+02:00] 	net/http/server.go:2042 +0x44               
ERRO[2021-08-25T15:41:35+02:00] github.com/ethersphere/bee/pkg/api.(*server).responseCodeMetricsHandler.func1(0x25fcb20, 0xc001b3bf50, 0xc00082b000) 
ERRO[2021-08-25T15:41:35+02:00] 	github.com/ethersphere/bee/pkg/api/metrics.go:71 +0xff 
ERRO[2021-08-25T15:41:35+02:00] net/http.HandlerFunc.ServeHTTP(0xc0005f31c0, 0x25fcb20, 0xc001b3bf50, 0xc00082b000) 
ERRO[2021-08-25T15:41:35+02:00] 	net/http/server.go:2042 +0x44               
ERRO[2021-08-25T15:41:35+02:00] github.com/gorilla/handlers.CompressHandlerLevel.func1(0x25fcb20, 0xc001b3bf50, 0xc00082b000) 
ERRO[2021-08-25T15:41:35+02:00] 	github.com/gorilla/handlers@v1.4.2/compress.go:148 +0x185 
ERRO[2021-08-25T15:41:35+02:00] net/http.HandlerFunc.ServeHTTP(0xc0005f31e0, 0x25fcb20, 0xc001b3bf50, 0xc00082b000) 
ERRO[2021-08-25T15:41:35+02:00] 	net/http/server.go:2042 +0x44               
ERRO[2021-08-25T15:41:35+02:00] github.com/ethersphere/bee/pkg/logging/httpaccess.NewHTTPAccessLogHandler.func1.1(0x2600120, 0xc000834460, 0xc00082b000) 
ERRO[2021-08-25T15:41:35+02:00] 	github.com/ethersphere/bee/pkg/logging/httpaccess/http_access.go:27 +0x12d 
ERRO[2021-08-25T15:41:35+02:00] net/http.HandlerFunc.ServeHTTP(0xc0002a9bd0, 0x2600120, 0xc000834460, 0xc00082b000) 
ERRO[2021-08-25T15:41:35+02:00] 	net/http/server.go:2042 +0x44               
ERRO[2021-08-25T15:41:35+02:00] net/http.serverHandler.ServeHTTP(0xc0001dcb60, 0x2600120, 0xc000834460, 0xc00082b000) 
ERRO[2021-08-25T15:41:35+02:00] 	net/http/server.go:2843 +0xa3               
ERRO[2021-08-25T15:41:35+02:00] net/http.(*conn).serve(0xc000616820, 0x26060e0, 0xc001b39100) 
ERRO[2021-08-25T15:41:35+02:00] 	net/http/server.go:1925 +0x8ad              
ERRO[2021-08-25T15:41:35+02:00] created by net/http.(*Server).Serve          
ERRO[2021-08-25T15:41:35+02:00] 	net/http/server.go:2969 +0x36c              
```

**Comment by mrekucci** [comment] 2021-08-25 14:40
Thanks for reporting this. Closing it because it is a duplicate of #2441

**Closed by mrekucci** 2021-08-25 14:40 UTC
Labels: issue, needs-triaging
