### ISSUE TITLE
Running out of disk space

### ISSUE THREAD

**Issue by alsakhaev** [ethersphere/bee#1258] opened 2021-02-15 16:06 UTC
#### Summary
We have a bunch of troubles running our bee node serving the swarm downloader (out hackathon project).
1) We a running a bee node under https://swarm.dapplets.org
2) the node takes all available space on HDD and obviously starts rejecting files we are uploading. Waiting for swarm hash either fails immediately or takes too long time.  We have set a db-capacity: 2621440 chunks (aprox. 10gb) + 5GB freespace, but goes fully consumed.

#### Steps to reproduce
1) Created VPS server in Hetzner with following hardware (CX11, 1 VCPU, 2 GB RAM, 20 GB) with Ubuntu 20.04.2 LTS
2) Installed Bee via `wget https://github.com/ethersphere/bee/releases/download/v0.5.0/bee_0.5.0_amd64.deb
sudo dpkg -i bee_0.5.0_amd64.deb`
3) Configured like in the config bellow
4) Installed nginx web-server and configured reverse proxy from https://swarm.dapplets.org to http://localhost:1633 with SSL of let's encrypt
5) Upload files to the node via POST https://swarm.dapplets.org/files/
6) After a while disk space runs out

#### Expected behavior
I expect to see 5gb freespace :)

#### Actual behavior
1) Disk space runs out
2) in the log a lot of errors about it
3) cannot upload a file, node responses HTTP 500 internal server error

#### Config /etc/bee/bee.yaml
Uncommented lines from config file:
```
api-addr: 127.0.0.1:1633
clef-signer-endpoint: /var/lib/bee-clef/clef.ipc
config: /etc/bee/bee.yaml
data-dir: /var/lib/bee
db-capacity: 2621440
gateway-mode: true
password-file: /var/lib/bee/password
swap-enable: true
swap-endpoint: https://rpc.slock.it/goerli
```

**Comment by Eknir** [comment] 2021-02-20 12:39
Thank you for reporting the bug! We will have a look into it shortly

**Comment by jpritikin** [comment] 2021-02-21 13:01
It should be pretty easy to calculate an approximate estimate of the maximum possible disk usage from `db-capacity` and compare that to the actual disk space available. If these are grossly out-of-whack then bee should log a suggestion of a new value for `db-capacity` that will not exceed the available disk space.

**Comment by jpritikin** [comment] 2021-02-22 11:28
I can reproduce this problem. It looks like disk space accounting does not include uploaded files. When I restart swarm, immediately a ton of disk space is freed up as `db-capacity` is re-applied.

**Comment by jpritikin** [comment] 2021-02-22 14:09
Hm, bee isn't releasing all of the disk space even after a restart,
````
root@salvia /o/bee# grep db-cap /etc/bee/bee.yaml
db-capacity: 5000000
root@salvia /o/bee# ls
keys/  localstore/  password  statestore/
root@salvia /o/bee# du -h -s .
111G	.
````

**Comment by acud** [comment] 2021-02-25 16:21
- Can you say if at any point your db capacity was set _above_ `5mil`?
- Did you play around with the size? 
Bee will not garbage collect your uploaded content before it is fully synced. You can track progress of your uploads with the tags API.

Please try to give as much information as to what you have done prior to this problem surfacing. 
I'm trying to reproduce this but so far no luck.

**Comment by jpritikin** [comment] 2021-02-25 16:36
> Can you say if at any point your db capacity was set above 5mil?

Yes, I tried 10mil. Once I realized that disk space management wasn't working then I reduced back to 5mil.

> Did you play around with the size?

On one node, I probably uploaded faster than sync'ing. For example, maybe I uploaded 30G of data to the node very quickly and then waited for it to sync.

> I'm trying to reproduce this but so far no luck.

If you can provide some guidance about how to not trigger the issue then that would also help. I gather that I shouldn't mess with the db-capacity setting. Also, I should not uploaded too fast?

I was trying to find where the limits were, to help with testing, but I am content to play within expected user behavior too.

**Comment by significance** [comment] 2021-03-16 09:47
@Eknir @acud 

message from bee-support

mfw78: I've found on 3x containers that I've run, all of them do not respect the db-capacity limit.

sig: are you uploading any data to them?

mfw78: No

**Comment by RealEpikur** [comment] 2021-03-16 20:54
+1: started a node on raspi with 32gb sd card, ran out of disk space after 10hrs

**Comment by ronald72-gh** [comment] 2021-03-16 21:01
+1: have set up docker-based nodes and all of their localstores have easily surpassed the db-capacity limit and use between 30Gb and 40Gb now

**Comment by mfw78** [comment] 2021-03-16 23:06
+1: Running multiple bees in Kubernetes containers. Each bee exhausts it's disk space allocation (doubling the db capacity has no effect besides chewing more space, and consequently exceeding).

**Comment by Eknir** [comment] 2021-03-23 08:08
Thanks all, for the comments and reports. We are releasing soon and included several improvements that aim to address this issue. We would greatly appreciate if you could try it out and report back here.

**Comment by mfw78** [comment] 2021-03-29 03:29
I can confirm that running 0.5.3 the `db-capacity` seems to be more respected, with 6 nodes that I'm running doing the following disk usage: 28G / 21G / 28G / 28G / 29G / 27G

**Comment by Eknir** [comment] 2021-04-06 07:27
This issue can be reliably reproduced with a rPI

**Comment by luowenw** [comment] 2021-04-08 05:06
<img width="176" alt="截屏2021-04-08 下午1 00 00" src="https://user-images.githubusercontent.com/9899031/113970926-5d0cb000-986a-11eb-89f3-f429a3d9b302.png">
I am running 0.5.3 using the default db-capacity. I can see the bee is doing garbage collecting in the same time of consuming more space. Once the garbage collecting fall off and the disk usage reached 100% then everything not working anymore. The log will keep reporting No Space Left and the garbage collecting will also stop to work.

**Comment by Eknir** [comment] 2021-04-13 10:09
@zelig @acud you guys are working on this as part of the postage stamps? 
Shall I assign this issue to the current sprint?

**Comment by Eknir** [comment] 2021-04-13 10:09
@zelig @acud you guys are working on this as part of the postage stamps? 
Shall I assign this issue to the current sprint?

**Comment by ethernian** [comment] 2021-04-18 18:37
the bug has a severe impact on the entire network because people are just purging the `localstore` of their nodes, causing data loss. No way to release the bee without killing the bug.

**Comment by tmm360** [comment] 2022-01-22 20:49
Any news on this? Issue is still there. I'm using default configuration on disk space (BEE_CACHE_CAPACITY=1000000), it should be ~4GB, but this is my disk space graphic.

![Immagine 2022-01-22 214259](https://user-images.githubusercontent.com/7620704/150654942-e8f734c2-d91a-4c4d-8c32-538383183ebf.png)

I didn't perform any upload on node. It's a VERY important issue to fix.

**Comment by acud** [comment] 2022-02-16 16:35
It should be resolved with the latest release. However the problem is multi tiered. If you `db nuke` your node and allow it to resync, the problem should be resolved.

**Comment by ldeffenb** [comment] 2022-02-16 17:09
Any plans to publish guidance on this?  In particular, how to detect if the issue exists within a node so that we don't just start nuking everything and dropping retrievability on chunks already stored in the swarm.

**Comment by tmm360** [comment] 2022-02-17 00:33
I've db nucked two of my nodes, let's see how it will evolve.

**Comment by agazso** [comment] 2022-03-22 15:12
@ldeffenb @tmm360 do you still experience this issue?

**Comment by jpritikin** [comment] 2022-04-06 19:39
I deleted the old database using `bee nuke`. Two weeks ago, disk usage was back to zero. As I write, disk usage is back up to 30GiB.

**Comment by jpritikin** [comment] 2022-04-06 21:41
Good amount of traffic today. Disk usage is up to 34.8GiB.

**Comment by jpritikin** [comment] 2022-04-07 20:04
I upgraded to 1.5.1 today. Disk usage is up to 47.9GiB. At this rate, I'll have to nuke my db again in a few weeks.

**Comment by ldeffenb** [comment] 2022-04-07 20:16
If you do the following command, substituting the proper IP and debug port, what value is displayed?  It should be 2 or 3 on testnet and 8 or 9 on mainnet.

`curl http://127.0.0.1:1635/topology | jq .depth`

**Comment by jpritikin** [comment] 2022-04-07 20:26
I'm on mainnet. Currently it says `6`

**Comment by ldeffenb** [comment] 2022-04-07 20:35
Are you sure you have inbound connections open and forwarded to your p2p-addr (default 1634)?  With a depth of only 6, it seems that you are not receiving inbound connections.  A shallower depth may cause your node to believe it needs to store more chunks as the neighborhood is larger.

**Comment by ldeffenb** [comment] 2022-04-07 20:38
Try the following command.  You should see at least one, hopefully more, inbound connections.   You may also need to set nat-addr if you are behind a NAT without UPNP capability.

`curl http://127.0.0.1:1635/topology | jq . | grep "inbound"`

**Comment by ldeffenb** [comment] 2022-04-07 20:39
Also, the following command should show "Public":

`curl http://127.0.0.1:1635/topology | jq .reachability`

**Comment by jpritikin** [comment] 2022-04-07 20:55
> curl http://127.0.0.1:1635/topology | jq .reachability

`"Public"`

> curl http://127.0.0.1:1635/topology | jq . | grep "inbound" | wc -l

`9`

> Are you sure you have inbound connections open and forwarded to your p2p-addr (default 1634)?

Yeah, pretty sure.

**Comment by ldeffenb** [comment] 2022-04-07 21:25
Ok, I'm out of ideas now.  Sorry, but the node is going to store what it thinks it needs to store. Nuking your DB periodically will just chew up your bandwidth and strain your neighborhood to push it all back to you, not to mention risking actually dropping the only copy of some chunks that your node was supposed to store.  Unless there's still a lurking issue with that somewhere that hasn't been uncovered and isn't visible with the metrics we currently have available.

**Comment by ldeffenb** [comment] 2022-04-07 21:30
One more final thought after having gone back through and re-read everything.  If you are still uploading through this node, are you asking it to pin the content on the upload?  Pinned content is not garbage-collected and is also not counted against the db-capacity configuration.  But it is all dropped on a db nuke, as far as I can tell.

**Comment by jpritikin** [comment] 2022-04-07 21:36
> Nuking your DB periodically will just chew up your bandwidth and strain your neighborhood

OK, I'm happy to wait until my disk fills up. Maybe devs will figure out a solution by then.

> If you are still uploading through this node

I am not. I haven't tried to upload for months.

**Comment by acud** [comment] 2022-05-02 17:17
@jpritikin I am adding a new `db indices` command to the binary so we can have a bit more info about the problem. Could you please build https://github.com/ethersphere/bee/pull/2924, run the `bee db indices --data-dir <path-to-data-dir>` and paste the output here?

**Comment by acud** [comment] 2022-05-02 17:28
also, @jpritikin please don't use that built version to run bee normally. use the current stable version to run bee with `bee start` (there are still some things that we're ironing out before the next release)

**Comment by jpritikin** [comment] 2022-05-02 21:46
Here is the output:
````
root@glow:~# ./bee db indices --data-dir /opt/bee
INFO[2022-05-02T17:19:40-04:00] getting db indices with data-dir at /opt/bee 
INFO[2022-05-02T17:19:40-04:00] database capacity: 1000000 chunks (approximately 20.3GB) 
INFO[2022-05-02T17:20:29-04:00] localstore index: gcSize, value: 950674      
INFO[2022-05-02T17:20:29-04:00] localstore index: retrievalAccessIndex, value: 1896105 
INFO[2022-05-02T17:20:29-04:00] localstore index: postageChunksIndex, value: 1896105 
INFO[2022-05-02T17:20:29-04:00] localstore index: retrievalDataIndex, value: 1896105 
INFO[2022-05-02T17:20:29-04:00] localstore index: gcIndex, value: 948228     
INFO[2022-05-02T17:20:29-04:00] localstore index: postageRadiusIndex, value: 703 
INFO[2022-05-02T17:20:29-04:00] localstore index: reserveSize, value: 957416 
INFO[2022-05-02T17:20:29-04:00] localstore index: pullIndex, value: 1895775  
INFO[2022-05-02T17:20:29-04:00] localstore index: pinIndex, value: 947877    
INFO[2022-05-02T17:20:29-04:00] localstore index: postageIndexIndex, value: 5173925 
INFO[2022-05-02T17:20:29-04:00] localstore index: pushIndex, value: 0        
INFO[2022-05-02T17:20:29-04:00] done. took 48.935545587s                     
````

**Comment by acud** [comment] 2022-05-02 23:02
w00t. and this takes how many gigs? can we have a `du -d 1 -h` of the localstore directory?

**Comment by jpritikin** [comment] 2022-05-02 23:17
Here you go,
````
root@glow:/opt/bee/localstore# du -d 1 -h
42G	./sharky
43G	.
````

**Comment by acud** [comment] 2022-05-03 01:46
can you also provide the output of your `/topology` endpoint on the debug api?

**Comment by jpritikin** [comment] 2022-05-03 16:20
Here is topology output, [topo.txt](https://github.com/ethersphere/bee/files/8611961/topo.txt)

**Comment by jpritikin** [comment] 2022-05-04 16:45
Like this? https://drive.google.com/file/d/1pSXKBGzcYKtAqRWFUDQb4-Z4uHiJUqSk/view?usp=sharing

**Comment by acud** [comment] 2022-05-04 22:59
thanks @jpritikin this was very helpful. i have some possible direction on the problem. since you can reproduce the problem, could you try the following please?
- have a look at the diff [here](https://github.com/ethersphere/bee/pull/new/jpritikin-bug)
- `git checkout v1.5.1` or the last stable release that you're running (if git complains and you can't see the tag do a `git fetch --tags`)
- apply the same change as in the changeset
- build the binary
- nuke the db
- run the binary as you normally would and see if the storage keeps on leaking

many thanks in advance!

**Comment by jpritikin** [comment] 2022-05-04 23:24
Okay, I'm running [this](https://github.com/makerdao-is/bee/tree/jpritikin-test) code.

**Comment by jpritikin** [comment] 2022-05-12 17:45
Disk usage is up to 21.5GiB.

**Comment by acud** [comment] 2022-05-12 19:53
@jpritikin so if I understand correctly everything is OK running with this fix?

**Comment by jpritikin** [comment] 2022-05-12 22:19
> so if I understand correctly everything is OK running with this fix?

No, I commented 4 hours ago because that's how long it took for the disk to fill up to that point. The test **begins** now, not ends.

Case in point, the disk usage is now up to 26GiB. So I would say that the fix has failed to cure the problem. :crying_cat_face:

**Comment by acud** [comment] 2022-05-13 02:06
The limit on amount of chunks stored is not a hard limit for reasons which would be difficult to explain here. Let's start with evaluating the size of the sharky sub directory over time. Please update us here on your findings. The leveldb part (the localstore root) also does not get GCd so often and when it does, it is done on its own conditions (not a full gc). Let's start from sharky dir stats then we see how to progress.

**Comment by jpritikin** [comment] 2022-05-13 02:37
Ah, well, maybe there is nothing wrong? Is this the output you need?

```
root@glow:/opt/bee/localstore# du -d 1 -h
17G	./sharky
18G	.
```

**Comment by jpritikin** [comment] 2022-05-16 16:21
Looks like I was confused by `df` output. `df` shows 35G used, but disk usage by the `sharky` directory is unchanged vs my previous comment 4 days ago. Time to close this issue?

**Comment by acud** [comment] 2022-05-17 10:38
Let's leave it open for now and continue tracking the issue

**Comment by jpritikin** [comment] 2022-05-17 13:56
Should I upgrade to v1.6 or is there still value in running the custom build?

**Comment by acud** [comment] 2022-05-18 07:10
yes you can, as we ported the fix into the release :+1:

**Comment by jpritikin** [comment] 2022-06-29 23:36
Hm, something is still broken? I upgraded to 1.6.2 today and noticed that the disk was filling up again,

```
root@glow:/opt/bee/localstore# du -d 1 -h
36G	./sharky
37G	.
```

**Closed** 2023-02-24 22:35 UTC
Labels: bug, issue
