### ISSUE TITLE
"Balanced" connector in Kademia isn't balanced

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#2521] opened 2021-09-16 22:09 UTC
#### Summary
While monitoring my 6 nodes in the mainnet, I noticed that 2 of them consistently have full bin zero connections (20) while the other 4 get up to 4 or 8 connections in bin zero and hover there.  For the node that only gets up to 4, it sometimes drops the depth from 12 to 0 if one of them disconnects and then the depth goes back to 12 once the bin 0 recovers to at least 4 connections.

Hint on a possible fix for this behavior is at the very bottom...

#### Steps to reproduce
Monitor the /topology low numbered bin connections across a random collection of peer IDs and you'll likely see the pattern.  You will want to expand their peer IDs to binary to see the string of zero bits (or not) beyond the first 3 or 4 bits of their peer IDs.

#### Expected behavior
I would expect the /topology bin connection counts to be independent of the peer ID, especially for low numbered bins in a large network like mainnet.  I mean, for bin 0, one half of the total swarm size are valid connection candidates!

#### Actual behavior
Because of the way the less-than-depth outbound connections are handled in kademlia.go's connectBalanced routine based on the proximity to commonBinPrefixes, there is a definite preference for connecting to peers with more zeroes just after their leading bits.  Peers with non-zero (one) bits in the most significant bits (after 3 or 4 bits) of their peer ID will not see as many incoming connections causing them to hover at or under saturationPeers and never come close to overSaturationPeers.

But peers with zeros in their most significant bits (after 3 or 4 bits) will nearly see a DOS attack as other nodes continually select them for "balanced" connections, even when they have long since reached their overSaturationPeers limit.  This can be observed by watching the "don't want incoming peer" messages in their logs.

My peer ID that starts with 6127 (0110 0001 0010) rejects 30 or more incoming peers every minute, 24x7:
```
time="2021-09-16T21:59:01Z" level=warning msg="stream handler: don't want incoming peer 44a499abfd9b214bf8171702bd2318f371ea76846ab76182faa3239e19455788. disconnecting"
time="2021-09-16T21:59:06Z" level=warning msg="stream handler: don't want incoming peer 735c85ea0cbb67e3af73269d11e8364800aa1e72538261da51bae0c1d3114915. disconnecting"
time="2021-09-16T21:59:07Z" level=warning msg="stream handler: don't want incoming peer 5821b89185402fceb01dcb0590c4862555e5ae44b6d5ea57f867464fbe91a3db. disconnecting"
time="2021-09-16T21:59:07Z" level=warning msg="stream handler: don't want incoming peer 6a14a6f83c35ac0ab4b741f9e6ec0602fbc31b9718ace58e1244b212a36ecece. disconnecting"
time="2021-09-16T21:59:09Z" level=warning msg="stream handler: don't want incoming peer 4516574135cd4ac2534d1a3e62c8497cefb12063b22d4ff970fe692e4e7f3e12. disconnecting"
time="2021-09-16T21:59:12Z" level=warning msg="stream handler: don't want incoming peer 5387927244cdd46b26bc310f7a396830322489198da98129be1d3df9a0a8eed6. disconnecting"
time="2021-09-16T21:59:14Z" level=warning msg="stream handler: don't want incoming peer 4c1dab82aecd53847654f27cb836da446ac3426f099c65ec37aa9d7dad1b1885. disconnecting"
time="2021-09-16T21:59:14Z" level=warning msg="stream handler: don't want incoming peer 503c1d320da915099000b26e643a73674c65a5de3e9d6913367ccf58f052bf4a. disconnecting"
time="2021-09-16T21:59:15Z" level=warning msg="stream handler: don't want incoming peer 6fe159f43725dfaa58978a4ed250372fff4c5d64fb720a4144e72b8c197a0c15. disconnecting"
time="2021-09-16T21:59:17Z" level=warning msg="stream handler: don't want incoming peer 73a196eb2865e704891360dae035a1a5611fb0135ecbd6a5bc8034ed1e5b2c03. disconnecting"
time="2021-09-16T21:59:22Z" level=warning msg="stream handler: don't want incoming peer 7ea2c360d12b4a6726c88daafad4b61b91f39711548f8cab9bef0228cccced3e. disconnecting"
time="2021-09-16T21:59:23Z" level=warning msg="stream handler: don't want incoming peer b2da2d72855c8d72d2486a216ca84b501bea8cf07ac60d4f88fe23e5e3893b5e. disconnecting"
time="2021-09-16T21:59:24Z" level=warning msg="stream handler: don't want incoming peer 750e3fbb29431611479561dcdb93c5a47651e56de5f7df75fce9d6164a1d7c41. disconnecting"
time="2021-09-16T21:59:27Z" level=warning msg="stream handler: don't want incoming peer 5ee1010a5baaa620c20644dcfb89b621d9912d882209d65f78ae7e28e08bb4ee. disconnecting"
time="2021-09-16T21:59:27Z" level=warning msg="stream handler: don't want incoming peer 7dc878ca0ae939436c52e73bc44740ff09016f87f7ed529f855672857a1e9dc7. disconnecting"
time="2021-09-16T21:59:29Z" level=warning msg="stream handler: don't want incoming peer 56f4ee09bd026103b466e96616858fa137c5763212c589c8475d0030a5c875c5. disconnecting"
time="2021-09-16T21:59:30Z" level=warning msg="stream handler: don't want incoming peer 40b0cdd5d4ef707bd6fd8076ad159a414cdecf8debf41b55967fedbabf65f9e9. disconnecting"
time="2021-09-16T21:59:32Z" level=warning msg="stream handler: don't want incoming peer 7f4fbb8efb1552f5c69718bb877045d128d3782349c754e7407630c427b8b1b6. disconnecting"
time="2021-09-16T21:59:34Z" level=warning msg="stream handler: don't want incoming peer c4a4c42f04aeab9dd1514153dd16b4cea9a796ae23cc5f4b36c758e6d32be794. disconnecting"
time="2021-09-16T21:59:36Z" level=warning msg="stream handler: don't want incoming peer 57d45329019550a9930c0ecbef63b2ec4ef6c0101e00097373007854874f7215. disconnecting"
time="2021-09-16T21:59:37Z" level=warning msg="stream handler: don't want incoming peer a567013bc49a485cea4f89454495a4653a77cbd94ff6038108a4d31e53b28ba3. disconnecting"
time="2021-09-16T21:59:40Z" level=warning msg="stream handler: don't want incoming peer 45c4f113802a9d6a83813895fe46b3c23ca62a5dc81cdf8a6fc9f88d19b739f5. disconnecting"
time="2021-09-16T21:59:40Z" level=warning msg="stream handler: don't want incoming peer 6b7582853730a72e18b50d18962dd960846395d482ba75cc1adbbf0080386543. disconnecting"
time="2021-09-16T21:59:40Z" level=warning msg="stream handler: don't want incoming peer 70c35bab5508728a12dc6fb630ccf348caca0eb1e96596f42b7c8df7a974769d. disconnecting"
time="2021-09-16T21:59:42Z" level=warning msg="stream handler: don't want incoming peer 537888f51511a2bcc0e77cd9fca0aacc261e4e3c367b7e2652805659b04bb0b0. disconnecting"
time="2021-09-16T21:59:46Z" level=warning msg="stream handler: don't want incoming peer 78231062313708e55cd4f910682a586d49e817d72c3ae3dd2b4717243439f9b7. disconnecting"
time="2021-09-16T21:59:48Z" level=warning msg="stream handler: don't want incoming peer 89977f0982e1f96cba2cf564a83c6e576908e31043ed1e56e8bce96962c83ae0. disconnecting"
time="2021-09-16T21:59:48Z" level=warning msg="stream handler: don't want incoming peer 735f4d3307f97ffe11067a1d290341814654dd420f991ac9b52abf59d47c8cf9. disconnecting"
time="2021-09-16T21:59:49Z" level=warning msg="stream handler: don't want incoming peer 5821b89185402fceb01dcb0590c4862555e5ae44b6d5ea57f867464fbe91a3db. disconnecting"
time="2021-09-16T21:59:51Z" level=warning msg="stream handler: don't want incoming peer 460b2e9542dbf20d5bdebdb8276580a7a3784fc6b384f95ed0c1e24e1401a4d1. disconnecting"
time="2021-09-16T21:59:51Z" level=warning msg="stream handler: don't want incoming peer 7bdbdf2c217ba7f3d33d2ae728dfb9f4b8bacde6e1e964b2b2c12baea5b7b272. disconnecting"
time="2021-09-16T21:59:54Z" level=warning msg="stream handler: don't want incoming peer 7d6561afbd33e1adecec4131164e663192d2cf7bdbf380e082d4b5cc42547354. disconnecting"
time="2021-09-16T21:59:56Z" level=warning msg="stream handler: don't want incoming peer 85d8ebeeea1a4b7902beebf71b92018c18213d39182fd5006e6bdc907ac47792. disconnecting"
time="2021-09-16T21:59:57Z" level=warning msg="stream handler: don't want incoming peer 51e010a4d21013ee8b4b384710118ec3c2ca3db67ba365e43887ae87f5a75b5f. disconnecting"
time="2021-09-16T21:59:58Z" level=warning msg="stream handler: don't want incoming peer 6924ec80a9872f4ff1e0af78f2acdca445a4f476bc97ce392dc5473c8c3eac6a. disconnecting"
time="2021-09-16T22:00:02Z" level=warning msg="stream handler: don't want incoming peer 75c21619cb64371367e8b0b36920054b30c8a1ee16267cbac086a9d707e8250b. disconnecting"
```

My peer ID that starts with d043 (1110 0000 0100) rejects 9-10 incoming peers every minute:
```
time="2021-09-16T22:56:02+01:00" level=warning msg="stream handler: don't want incoming peer 5cca426509bc17c40bd8d82503fb1ca0d5f2e1f9f38a481046ea3113c139afa5. disconnecting"
time="2021-09-16T22:56:05+01:00" level=warning msg="stream handler: don't want incoming peer 7bd02afd29ce1a93b950b525bb68e3a66d3bfb0fbe036bbe099fb55a55581cc6. disconnecting"
time="2021-09-16T22:56:05+01:00" level=warning msg="stream handler: don't want incoming peer bb966f0740300ef96d607ff25d6e0d00b250699161c894e045e8cbf28f91a49f. disconnecting"
time="2021-09-16T22:56:10+01:00" level=warning msg="stream handler: don't want incoming peer afecc8e90326558b086c2f2018e7c073d6f664fdfd86561620774d20e10cbc3c. disconnecting"
time="2021-09-16T22:56:16+01:00" level=warning msg="stream handler: don't want incoming peer 0ba945c37d37eb52ea196031c78fa569bb0a3d4f54aaf902c261c3a33aee550f. disconnecting"
time="2021-09-16T22:56:17+01:00" level=warning msg="stream handler: don't want incoming peer d3e69e727b309c81d3141c7c6722c97b8ce61c8e0b07651eeb10cfac581ca30a. disconnecting"
time="2021-09-16T22:56:19+01:00" level=warning msg="stream handler: don't want incoming peer 8945b81873b0403d7519bd0fb54b118f7b7404af145ffb5da47cb917a5e009bf. disconnecting"
time="2021-09-16T22:56:25+01:00" level=warning msg="stream handler: don't want incoming peer ffe4acb3b9b3d7298382727efadb42bf06f40dbaa5395b40dfd698da47ad1c63. disconnecting"
time="2021-09-16T22:56:26+01:00" level=warning msg="stream handler: don't want incoming peer 39adb72864e50e9bcb00f67da68039706a34d4ad635ce5131aecd4245b330964. disconnecting"
time="2021-09-16T22:56:39+01:00" level=warning msg="stream handler: don't want incoming peer d1991b01f8b72c60991924bef08d0253cf6b442f0bb608748362742943857f55. disconnecting"
time="2021-09-16T22:56:42+01:00" level=warning msg="stream handler: don't want incoming peer 8c56c548c1a9ad4a6fc895757a89d536bbe65aaad64819c9bf5392ff9f97841f. disconnecting"
time="2021-09-16T22:56:53+01:00" level=warning msg="stream handler: don't want incoming peer f6b68a1cc8a12856c4d8eb00dc958d7a832e68dceb28dffd64e3433386aeb198. disconnecting"
time="2021-09-16T22:56:56+01:00" level=warning msg="stream handler: don't want incoming peer d267194cc6f4a46a415d5d0bd1b6f416b4540099697eb553fac43f46a929443c. disconnecting"
time="2021-09-16T22:57:01+01:00" level=warning msg="stream handler: don't want incoming peer ebc71bdbb64c31fca2bba53f406e092cefc7fa8d736f31e360c1463ded3a41fb. disconnecting"
time="2021-09-16T22:57:01+01:00" level=warning msg="stream handler: don't want incoming peer 95a014f665d27dfe41bb917c062da0be34bc2f0d4d3ea128b8ade82f5813ae7c. disconnecting"
time="2021-09-16T22:57:19+01:00" level=warning msg="stream handler: don't want incoming peer c9351d37d913f5f21719742459f760cbc4a42d9af11f0152df9af0315c90d964. disconnecting"
time="2021-09-16T22:57:19+01:00" level=warning msg="stream handler: don't want incoming peer 46df426975045d9b3cf6d3e06859b9c1eab157f1e5b5f69aea81295ea6bc1538. disconnecting"
time="2021-09-16T22:57:21+01:00" level=warning msg="stream handler: don't want incoming peer 91a79ad23d3531455a674297022c9f2a3efa5b810bafef3eb8032a1823f2642c. disconnecting"
time="2021-09-16T22:57:23+01:00" level=warning msg="stream handler: don't want incoming peer de22bd82c2cc29ae38b434e8dfc897cd650a8ebb11dffdbd771ea8767ee6ce2f. disconnecting"
time="2021-09-16T22:57:26+01:00" level=warning msg="stream handler: don't want incoming peer d38bb5952ba41e962295eb16d9fed6988efee0479f054a7b90c563c030631753. disconnecting"
time="2021-09-16T22:57:31+01:00" level=warning msg="stream handler: don't want incoming peer fb50e24816a25d664707304a961f0c3bd7bab76e9fc4e5621c171cefe42b4005. disconnecting"
time="2021-09-16T22:57:35+01:00" level=warning msg="stream handler: don't want incoming peer d3e69e727b309c81d3141c7c6722c97b8ce61c8e0b07651eeb10cfac581ca30a. disconnecting"
```

By contrast, my other 4 peers with the following IDs seem to never reject a single incoming peer:
e7e7 1110 0110 1110
0d46 0000 1101 0100
2128 0010 0001 1000 (Not sure why this one doesn't see the behavior)
cb36 1100 1011 0110

Peers with a lot of zeros following the first 3 or 4 bits of their peer ID will see more incoming connections, likely more than their overSaturationPeers will allow.

#### Possible fix
I suspect this can be fixed by randomizing the trailing zero bits that are currently generated by generateCommonBinPrefixes in pkg\topology\kademlia\binprefix.go, in particular the final loop that says "clear rest of the bits".  It is these trailing bits that results in the preference for zero bits following the prefix in outbound connections which then results in the oversaturation of peers that happen to have these zero bits in their peer ID.

Note that you are NOT likely to see this in the testnet because there just aren't enough peers in the swarm to accentuate the behavior!

**Comment by ldeffenb** [comment] 2021-11-16 02:25
Does any core developer have any comments on this one?  It's definitely a happening behavior with unintentional side effects.

**Comment by istae** [comment] 2021-11-16 15:36
The idea behind the balanced connector is to have, in each bin, 8 peers with different combinations of 3 bits following the initial bin number of bits. 
Example for bin 0: 0000, 0001, 0010 ....etc

That being said, no special preference is given to a combination.

My initial observation was that because your address has 4 zeros in a row, your node could be used to balance two (not one) bins by the network, but the fact your 2128 node does not see this behavior is strange.

**Comment by metacertain** [comment] 2021-11-23 03:22
your description is I think legitimate, the trailing zeroes make nodes balancing their connections biased towards addresses with more consecutive zeroes following the suffix bits, and having a longer than four in a row of 0s makes your address overly popular for now. having the 0 row in earlier bits means more nodes would find you a suitable connection. the first significant bit is the 5th as the prefix + suffix is minimum 4 bits

we can change this by randomizing these bits and make addresses less prefered based on this property

**Comment by ldeffenb** [comment] 2021-11-23 12:21
@metacertain Thanks for the confirmation!  And the randomization of the bits beyond the balance target bits is precisely what I figured would remove this preferential treatment of the zero-bit addresses.

**Comment by ldeffenb** [comment] 2022-02-06 03:14
Still wishing this would get fixed to better distribute the peer connections...

**Comment by acud** [comment] 2022-06-09 11:26
I think we can close this since indeed the problem should be solved. @ldeffenb please reopen if this is still a thing (or a regression has happened).

**Closed by acud** 2022-06-09 11:26 UTC
Labels: issue, needs-triaging
