### ISSUE TITLE
Storage space isolation

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#853] opened 2020-10-21 14:14 UTC
# User story

## Story
The underlining stories are related. Depending on how this task can be best split, we should make separate issues from them and track those.

**file upload**
As file uploader, I want that a big upload doesn't make my node to garbage-collect stuff which I am supposed to store.
file upload should neither take up arbitrary space, nor be impossible to use.

**local pin allocation**
As a local pinner and storer node, I want that the content which I am locally pinning doesn't interfere with my in-neighborhood storage capacity, such that my in-neighborhood storage is not garbage-collected if I am pinning too much

**Cache-store vs neighborhood store**
As an economically incentivized storer node, I want to seperately control the size of my in-neighborhood storage and cache-storage, such that I can optimize my profit per chunk and my cached chunks don't interfere with my in-neighborhood chunks

## Acceptance criteria

Various reasons to store chunks (pin, cache, in neighborhood store) should never be able to interfere with each other, unless the user explicitly meant to.

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by Eknir** [comment] 2020-10-28 10:51
- As part of this task, we decided (pending @janos approval) that push sync doesn't go via localstore (@acud willl verify how difficult this is)
- We have a total allowance for storage. This consists of reserve (in neighborhood storage) and cache (FIFO) model, with retrieval putting it on top again)
- The ratio of reserve/cache changes, based on information from the price oracle (which determines the required storage capacity for reserve)
- Pinning: if you use local pinning, it goes beyond the storage allowance
- we should not bother to add a failsafe (for now)
- There needs to be debug API endpoints or metric to communicate the size of each storage (cache, pinning, reserve)

**Comment by Eknir** [comment] 2020-10-28 11:04
About reserve/cache: 	
https://hackmd.io/2NgPR2CeQICKzWBAH7Mk0Q?both

**Comment by janos** [comment] 2020-10-28 11:56
I see loosing the persistence of pushsync as a regression in feature, as uploaded data will not reach the network if the user restarts the node, but I am fine with that decision if it would make things less difficult. The reason why all of our indexes are in a single leveldb instance is the lack of transactions to ensure consistency of chunk data and relations. Push sync index can be in a different database later, which would be more modular approach, but would present challenges to ensure data consistency between chunk storage and push sync index.

Getting the size of the database of some part of it is not performant with leveldb. Basically full iterations should be done, over the all key/value pairs of over some index (already implemented in shed). This will linearly influence the debug api storage size endpoint performance with the data size.

In general, I am fine with these points as they are.

**Comment by ldeffenb** [comment] 2020-10-28 13:45
> I see loosing the persistence of pushsync as a regression in feature, as uploaded data will not reach the network if the user restarts the node

Personally, I think that is a serious regression.  I suspect it will not be uncommon that someone uploads a large-ish file and for some reason restarts their node before the push is complete.  If the push index is not persistent, then that file will not be retrievable except via global pinning, and that's only if the uploading node is configured that way.  Or is there something I'm missing?

As I've posted elsewhere, I have a node that is still trying to finish a push sync since the beginning of October and the node has been restarted numerous times.  As I understand it, without a persistent push sync index, the uploaded pending push would have terminated on the first restart rendering the file never fully in the network.  Granted, it's not fully in the network now (yet), but I'm ever the optimist that whatever target node is causing the stream resets to the pusher will eventually go away or fix itself.

**Comment by Eknir** [comment] 2021-01-24 15:52
Related #1137

**Comment by acud** [comment] 2021-04-27 06:54
this is resolved with storage incentives PR to a satisfactory degree from my side. I'm moving this ticket to `Done`

**Closed** 2021-05-21 13:14 UTC
Labels: issue
