### ISSUE TITLE
pushsync: chunk  context deadline exceeded

### ISSUE THREAD

**Issue by cppfuns** [ethersphere/bee#1702] opened 2021-05-13 11:20 UTC
ay 13 19:18:21 web204_234 bee[20445]: time="2021-05-13T19:18:21+08:00" level=warning msg="peer not reachable when attempting to connect"
May 13 19:18:21 web204_234 bee[20445]: time="2021-05-13T19:18:21+08:00" level=info msg="attempting to connect to peer 40031416ea7b95cf2c2d2d217e9928e5defb95c6c274423820c1021538a9bea0"
May 13 19:18:23 web204_234 bee[20445]: time="2021-05-13T19:18:23+08:00" level=warning msg="peer not reachable when attempting to connect"
May 13 19:18:23 web204_234 bee[20445]: time="2021-05-13T19:18:23+08:00" level=info msg="attempting to connect to peer 800ffca1d588c7a246cbaa1b557f1c6a32a9c6ef8ecb6bf97008abe3b11b162b"
May 13 19:18:25 web204_234 bee[20445]: time="2021-05-13T19:18:25+08:00" level=warning msg="peer not reachable when attempting to connect"
May 13 19:18:25 web204_234 bee[20445]: time="2021-05-13T19:18:25+08:00" level=info msg="attempting to connect to peer 90001faf80cc959027b6cce4468076357790a11bebd0822c82229ca33bd457f3"
May 13 19:18:27 web204_234 bee[20445]: time="2021-05-13T19:18:27+08:00" level=warning msg="peer not reachable when attempting to connect"
May 13 19:18:27 web204_234 bee[20445]: time="2021-05-13T19:18:27+08:00" level=info msg="attempting to connect to peer c00d229f21bb13e3ca1cb2ed40a6288581fe4537b039bea66e4000d9a9e9a144"
May 13 19:18:32 web204_234 bee[20445]: time="2021-05-13T19:18:32+08:00" level=warning msg="peer not reachable when attempting to connect"
May 13 19:18:32 web204_234 bee[20445]: time="2021-05-13T19:18:32+08:00" level=info msg="attempting to connect to peer c80058f63e1793e5526d9012c8bc34e6019db84436149ac7142f8d8352d29a2e"
May 13 19:18:34 web204_234 bee[20445]: time="2021-05-13T19:18:34+08:00" level=warning msg="peer not reachable when attempting to connect"
May 13 19:18:34 web204_234 bee[20445]: time="2021-05-13T19:18:34+08:00" level=info msg="attempting to connect to peer d0042198a88a4e252cb9b2d5513a488e87fab53381f5c80aa19a7e148aff0bbc"
May 13 19:18:35 web204_234 bee[20445]: time="2021-05-13T19:18:35+08:00" level=warning msg="peer not reachable when attempting to connect"
May 13 19:18:35 web204_234 bee[20445]: time="2021-05-13T19:18:35+08:00" level=info msg="attempting to connect to peer e400bcf0be32fc93f234f16fbfcfcba60343f29dfa374eac7c0992c7891f9828"
May 13 19:18:37 web204_234 bee[20445]: time="2021-05-13T19:18:37+08:00" level=error msg="pushsync: chunk fb01cc0f45441f4dc7755694af4389d0eb463f7e0e996710924bbff475319140 receive receipt from peer fb00a1d79fdfb6a5837caa5282b365f5437f531c9e930ee2b71db61304793c5d: context deadline exceeded"
May 13 19:18:38 web204_234 bee[20445]: time="2021-05-13T19:18:38+08:00" level=warning msg="peer not reachable when attempting to connect"
May 13 19:18:38 web204_234 bee[20445]: time="2021-05-13T19:18:38+08:00" level=info msg="attempting to connect to peer e80958e1d7f681e554e1e56dc495ee95fe41e079bceac142a546e7264df8b206"
May 13 19:18:39 web204_234 bee[20445]: time="2021-05-13T19:18:39+08:00" level=error msg="pushsync: chunk fb95487ce7c3ae0901cc58b0025b1dcf04515266731080baee7f5d3cdb38a568 receive receipt from peer fb82921f71416971dda949c607f7d48a3aa3b39ceb33c0ced28fe8a5b2ffa10f: context deadline exceeded"
May 13 19:18:41 web204_234 bee[20445]: time="2021-05-13T19:18:41+08:00" level=warning msg="peer not reachable when attempting to connect"
May 13 19:18:41 web204_234 bee[20445]: time="2021-05-13T19:18:41+08:00" level=info msg="attempting to connect to peer f00115ae6a6760d09c57ce17fa39b46cb3f67dd5bc74709557390459b1f3001a"
May 13 19:18:42 web204_234 bee[20445]: time="2021-05-13T19:18:42+08:00" level=error msg="pushsync: chunk fa81015f389f4d988bce8e14d3bf8ceaf527263ae9da3589f4c0ed097052ddd1 receive receipt from peer fa81a51dfdec6a693caa6ca0f6daef3208b3c5d12abede8f915995c06285ad57: context deadline exceeded"
May 13 19:18:43 web204_234 bee[20445]: time="2021-05-13T19:18:43+08:00" level=warning msg="peer not reachable when attempting to connect"
May 13 19:18:43 web204_234 bee[20445]: time="2021-05-13T19:18:43+08:00" level=info msg="attempting to connect to peer f4042de73d683c5123cd42b78c70b3b80640b32938c9002b537e3163778ad973"
May 13 19:18:45 web204_234 bee[20445]: time="2021-05-13T19:18:45+08:00" level=warning msg="peer not reachable when attempting to connect"
May 13 19:18:45 web204_234 bee[20445]: time="2021-05-13T19:18:45+08:00" level=info msg="attempting to connect to peer fd008ecc0a8bff14473767956cdb1d33f6f7b7dad8bff2fc2029b9e24e5b0311"
May 13 19:18:46 web204_234 bee[20445]: time="2021-05-13T19:18:46+08:00" level=error msg="pushsync: chunk fa8c17e821eb99157b94fcbb7fd84aef27cf524ab996fe5194a84f2b114ecf2b receive receipt from peer fa8d1c76296d29f05fb36bcfc1fadf60dc44459d7260cfef87b60fc57162024e: context deadline exceeded"
May 13 19:18:46 web204_234 bee[20445]: time="2021-05-13T19:18:46+08:00" level=warning msg="peer not reachable when attempting to connect"
May 13 19:18:46 web204_234 bee[20445]: time="2021-05-13T19:18:46+08:00" level=info msg="attempting to connect to peer fe00ac3fd676a2b8724bdbf98cb68089c8c0c6eba5a30daa121491b920f94874"
May 13 19:18:47 web204_234 bee[20445]: time="2021-05-13T19:18:47+08:00" level=error msg="pushsync: chunk f8ece7c2ac386ad35b9bf150adb57c413d23061bc1668a22c61214313e921e20 receive receipt from peer f9fc1b8385c95d2dfaeb692cf952ad32776fe257e92c53bba44f47b77cd99c09: context deadline exceeded"
May 13 19:18:47 web204_234 bee[20445]: time="2021-05-13T19:18:47+08:00" level=error msg="pushsync: chunk fa971dc6ba322b1e9fe5acd3db9739c3c8f6fc52adbdb34ec2c26e2b7dc4a399 receive receipt from peer fa9705e79abd4f685fa21dd9cedb320ccebbdf1e340c6b73eefdff73e932a44a: context deadline exceeded"
May 13 19:18:48 web204_234 bee[20445]: time="2021-05-13T19:18:48+08:00" level=warning msg="peer not reachable when attempting to connect"
May 13 19:18:49 web204_234 bee[20445]: time="2021-05-13T19:18:49+08:00" level=info msg="attempting to connect to peer f808815d7162ba7c189378dbe6b4052a7bbccce8a84084d8c9ac1d1a2b926e42"

**Comment by maketigers** [comment] 2021-05-18 02:50
same bug,how to fix ?

**Comment by potato1992** [comment] 2021-05-28 03:27
same

**Comment by meaverick** [comment] 2021-06-01 15:51
what's solution?

**Comment by Eknir** [comment] 2021-07-09 07:39
Hi all,
Thank you for the comment and for reporting this. 

The issue is that in Swarm, nodes collaborate in routing *chunks* to the destination in the network. If some nodes take longer than expected, this happens.

This issue is a very general problem and we are well aware of it. With 1.0, this is improved, but still not idea. I am closing the issue, as it is not directly actionable by neither you nor us, but rest assured that we are working on this.

**Comment by cppfuns** [comment] 2021-07-09 07:44
> Hi all,
> Thank you for the comment and for reporting this.
> 
> The issue is that in Swarm, nodes collaborate in routing _chunks_ to the destination in the network. If some nodes take longer than expected, this happens.
> 
> This issue is a very general problem and we are well aware of it. With 1.0, this is improved, but still not idea. I am closing the issue, as it is not directly actionable by neither you nor us, but rest assured that we are working on this.

Should we wait for the real fix and let the user who submitted the issue verify before closing the issue? Don’t actively close the question for the sake of fewer problems

**Closed** 2021-07-09 11:35 UTC
Labels: bug, issue
