### ISSUE TITLE
File permissions unexpectedly change on clef.ipc 

### ISSUE THREAD

**Issue by angst7** [ethersphere/bee#1271] opened 2021-02-16 19:44 UTC
#### Summary
When starting the bee service, the clef signer cannot be accessed: it returns a permission denied error (This may be the same root cause as #1263 ).  Manually changing group permissions only seems to work temporarily -- the file permissions get automatically reverted.

#### Steps to reproduce
Start the bee service.  
Check the logs: The logs indicate that the service cannot connect to the clef signer: permission denied.
Manually update the permissions with: sudo chmod 660 /var/lib/bee-clef/clef.ipc 
Restart the bee service.
The bee service successfully connects to the clef signer.
After a few moments, check the permissions and see:
srw-------  1 bee-clef bee-clef    0 Feb 16 19:16 clef.ipc

#### Expected behavior
Permissions are retained, or otherwise properly managed.

#### Actual behavior
Permissions revert to incorrect group settings.

**Comment by angst7** [comment] 2021-02-16 19:51
Update:  A possible work-around is to *not* restart the bee service after changing the permissions manually.  i.e. running the bee service, then manually changing the permissions appears to retain the group permissions.  So this is possibly related to some startup behavior in the bee service.
I have two previously non-working servers running now, using this work-around.

**Comment by ldeffenb** [comment] 2021-02-20 03:16
Typo in the chmod command:
sudo chmod 660 /var/lib/bee-clef/clef.ibc
should be:
sudo chmod 660 /var/lib/bee-clef/clef.ipc

IPC not IBC.

**Comment by angst7** [comment] 2021-02-20 03:59
Edited the original, thanks!

**Comment by Eknir** [comment] 2021-02-20 13:28
@angst7 - Thanks for taking the time to report this issue!

@rpicc, is this a duplicate of #1263 ? If so, can you please close this issue? Thanks

**Comment by angst7** [comment] 2021-02-20 16:34
I'll add a little more about this, if its helpful.  Whatever is doing the reverting of the permissions seems to be related to connecting to peers.  When the node first starts up and is trying to connect to peers, the file permissions are getting reset quite often -- during this time there's quite a bit of interaction with bee-clef.  Once the number of peers gets to 30-40 or so things seem to settle down, and the permissions stay.  It's as if some outcomes of a peer connection attempt cause the permission reset, while others leave it alone.

**Comment by angst7** [comment] 2021-02-20 17:02
This may be down to an the clef service restarting a little after the chmod command from the bee-clef-service script is executed.  I increased the chmod delay from 4 to 10 and it appears to have resolved the issue on my most troublesome node:

`    (sleep 10; chmod 660 /var/lib/bee-clef/clef.ipc) &`

**Comment by attila-lendvai** [comment] 2021-02-21 18:27
@angst7 first and foremost, please let us know the exact versions of the packages that you are using, and the host operating system.

**Comment by attila-lendvai** [comment] 2021-02-21 19:46
FTR, it is `clef` that changes file permissions at each restart, and i think it's either already fixed, or will be addressed soon.

**Comment by attila-lendvai** [comment] 2021-02-23 09:15
my PR got merged into bee-clef (thank you for testing it!), and it will soon be released (days).

closing this, but feel free to reopen if the problem persists after the release.

**Closed by attila-lendvai** 2021-02-23 09:15 UTC
Labels: bug, issue

**Comment by ShilohMy** [comment] 2021-06-05 15:31
Error: open /var/lib/bee/password: permission denied
