### ISSUE TITLE
Test race detector fail in mac os in CI

### ISSUE THREAD

**Issue by jmozah** [ethersphere/bee#489] opened 2020-07-28 16:24 UTC
CI failed while running the "file-tags" branch in [this](https://github.com/ethersphere/bee/pull/393) PR
It failed in mac os only in  "Test race detector"

https://github.com/ethersphere/bee/pull/393/checks?check_run_id=919621277

=== RUN   TestBroadcastPeers/OK_-_single_batch_-_max_number_of_records
##[error]    hive_test.go:207: Overlays got [137ffddb14f79c095c180249c55ae12fcf4744557ccb3b47a74ad5cc66540882 6e76765489bd313cbb6a00b6d643f84768bb397f0700ca93a4a42b37a0c1687c 4821fadf8b319027d1ee5dadbb4303edbe693481c2db219cd268df7c30931bd0 bddf772ae51977ae67ed82cba161876914b384e5783135615f6d8b5259b0e588 40f091982b075cb12843a6b34f1442cd631d4242341f579397e5d5fd94808acd c36cf3328724f203bff31592a4e6e646227987f7a76592f8384308ff140b20ec 0184e8248b846e4f1e4d58e23e1784a8f86388d033dac807637f474eadab6e29 af38ce26182a06b0eec8ac956acb95c4f32f716764b3e6f5d52a7fd99a7bb5c2 6dfdce03e12ec3f37cb2ad5a0131741669b5aebab5fa52e1fa8299cc47af187c c380ad7a3e2ad61a670bf49fd0aef63f2854bf439aed1abcbdd12981f778b9ab cb40bbb3cc862c7ee287e43f3ffbadd32f3ecd4d7a886009a99e580959aadb7b 869b277c5c0157b8aeed1ebb6c8c3b715606a3bd66029a3e510b5f72e4a416d3 89e6d7b84cc416762a41b416cccde730579b2cfde7be8ce3b6c99c37105e8abf 039da41553f86793f4149de008805bd949e5337ffbc75b240c853c810789f088 2a7efd4bf1da88fda98c281c97ad797322704f752708c228a653a05aebcf5d1c 8a60e3e4b0603833aa891ac429b2eb23cfebdc536115740aefd95ddaca693950 712e855ab603fe12376fd24015ed77456580b5d4318b4f137748bd14a4b3d45b f9e32ae702a1166ae82794317301acfac30070658148f3ad6c2c8f37dd2f577d 53663ecf8c19459dcd2374a2c234941ae9b0bc7a2eb3030ecd0377e414607b43 35368e62eb6c3ed2706279f98ced41a960b4962b18391d1fc1b8e31a268e093d 500ea80ad47d99f774e88922c0ef2a610fe54b83c2248244208130d3951f109a 6ded19f3fe623f5ba6fa4b02d1bb5484b5bf963a861ac992e6283eb938673c82 c9f29c0810898c61a03b7783a301f53eec23c1376dea4f2ffb517ae810e2ad3f 4c559008a116e51952086184c79f437f645be707a4fe2b885a0c8b29e23101ad b701f71bee362f71eba01446935b619ff5b7d81de5f6af2bf41238c7e7d54c8f], want 
[89e6d7b84cc416762a41b416cccde730579b2cfde7be8ce3b6c99c37105e8abf 039da41553f86793f4149de008805bd949e5337ffbc75b240c853c810789f088 c9f29c0810898c61a03b7783a301f53eec23c1376dea4f2ffb517ae810e2ad3f 2a7efd4bf1da88fda98c281c97ad797322704f752708c228a653a05aebcf5d1c af38ce26182a06b0eec8ac956acb95c4f32f716764b3e6f5d52a7fd99a7bb5c2 4c559008a116e51952086184c79f437f645be707a4fe2b885a0c8b29e23101ad 40f091982b075cb12843a6b34f1442cd631d4242341f579397e5d5fd94808acd b701f71bee362f71eba01446935b619ff5b7d81de5f6af2bf41238c7e7d54c8f c36cf3328724f203bff31592a4e6e646227987f7a76592f8384308ff140b20ec 0184e8248b846e4f1e4d58e23e1784a8f86388d033dac807637f474eadab6e29 f9e32ae702a1166ae82794317301acfac30070658148f3ad6c2c8f37dd2f577d 53663ecf8c19459dcd2374a2c234941ae9b0bc7a2eb3030ecd0377e414607b43 35368e62eb6c3ed2706279f98ced41a960b4962b18391d1fc1b8e31a268e093d 6dfdce03e12ec3f37cb2ad5a0131741669b5aebab5fa52e1fa8299cc47af187c 137ffddb14f79c095c180249c55ae12fcf4744557ccb3b47a74ad5cc66540882 6e76765489bd313cbb6a00b6d643f84768bb397f0700ca93a4a42b37a0c1687c c380ad7a3e2ad61a670bf49fd0aef63f2854bf439aed1abcbdd12981f778b9ab cb40bbb3cc862c7ee287e43f3ffbadd32f3ecd4d7a886009a99e580959aadb7b 4821fadf8b319027d1ee5dadbb4303edbe693481c2db219cd268df7c30931bd0 869b277c5c0157b8aeed1ebb6c8c3b715606a3bd66029a3e510b5f72e4a416d3 500ea80ad47d99f774e88922c0ef2a610fe54b83c2248244208130d3951f109a bddf772ae51977ae67ed82cba161876914b384e5783135615f6d8b5259b0e588 8a60e3e4b0603833aa891ac429b2eb23cfebdc536115740aefd95ddaca693950 6ded19f3fe623f5ba6fa4b02d1bb5484b5bf963a861ac992e6283eb938673c82 712e855ab603fe12376fd24015ed77456580b5d4318b4f137748bd14a4b3d45b ab23bde4d295bdd0fd2b094345ee8741422bc293ef1a6f583b1e841b66c012a5 ee89234d7c5397d0b4ddcd7b65c454deb1886481286b032623d62b55df1a19e9 8f3f4ef4358c88d7c21fe8e81856fe26642ec8af9472b0175c7b13f71a921079 8366d3871a3e8ea81c20ed3c4fbc481f986fcf24f770209cd6e3242763854b6b 8e0ac2b5e4261ff83e396c1988a04752caf9fea067ab1e391eb51d4758567d2b]
=== RUN   TestBroadcastPeers/OK_-_multiple_batches
##[error]    hive_test.go:207: Overlays got [b4a2b1d3a48568ec34f22a81b4443842ebbfab744dcfb0ca90d4eba6500ccab3 5efb98122f57546e576dd9183610ca210041f663572af95bdf635f3dc009c8ee 712e855ab603fe12376fd24015ed77456580b5d4318b4f137748bd14a4b3d45b 039da41553f86793f4149de008805bd949e5337ffbc75b240c853c810789f088 b4537466075ac17f7a1d9d0a094f518d68730c35ea6f9a7fb30e4c894a816cb5 137ffddb14f79c095c180249c55ae12fcf4744557ccb3b47a74ad5cc66540882 c380ad7a3e2ad61a670bf49fd0aef63f2854bf439aed1abcbdd12981f778b9ab cbf8691c4d68210bffd39bf278416504a134172ab1e8e7d2c5349f066804eedc 82cb49c0e5af5dbfd7281494e21ad07d5b06b15e8b857fe1167a4bdee817b1a6 0184e8248b846e4f1e4d58e23e1784a8f86388d033dac807637f474eadab6e29 6ded19f3fe623f5ba6fa4b02d1bb5484b5bf963a861ac992e6283eb938673c82 c2d4eb02ac5f3f1cac5a3376ad037a2dead68d2a03b229ed7d4188e368079b49 467bcc2cf2d7196d6386b5b0e58dd9666658059d741ae40c0239492b9ef0b6a4 4c559008a116e51952086184c79f437f645be707a4fe2b885a0c8b29e23101ad c36cf3328724f203bff31592a4e6e646227987f7a76592f8384308ff140b20ec 6dfdce03e12ec3f37cb2ad5a0131741669b5aebab5fa52e1fa8299cc47af187c 6e76765489bd313cbb6a00b6d643f84768bb397f0700ca93a4a42b37a0c1687c cb40bbb3cc862c7ee287e43f3ffbadd32f3ecd4d7a886009a99e580959aadb7b 8a60e3e4b0603833aa891ac429b2eb23cfebdc536115740aefd95ddaca693950 c9f29c0810898c61a03b7783a301f53eec23c1376dea4f2ffb517ae810e2ad3f af38ce26182a06b0eec8ac956acb95c4f32f716764b3e6f5d52a7fd99a7bb5c2 f9e32ae702a1166ae82794317301acfac30070658148f3ad6c2c8f37dd2f577d 869b277c5c0157b8aeed1ebb6c8c3b715606a3bd66029a3e510b5f72e4a416d3 bddf772ae51977ae67ed82cba161876914b384e5783135615f6d8b5259b0e588 2a7efd4bf1da88fda98c281c97ad797322704f752708c228a653a05aebcf5d1c 40f091982b075cb12843a6b34f1442cd631d4242341f579397e5d5fd94808acd b701f71bee362f71eba01446935b619ff5b7d81de5f6af2bf41238c7e7d54c8f 53663ecf8c19459dcd2374a2c234941ae9b0bc7a2eb3030ecd0377e414607b43 35368e62eb6c3ed2706279f98ced41a960b4962b18391d1fc1b8e31a268e093d 89e6d7b84cc416762a41b416cccde730579b2cfde7be8ce3b6c99c37105e8abf e61d0ffdff3e77954a5581d532ba45621a9961c564b77905d4a0992acecbc44c 4821fadf8b319027d1ee5dadbb4303edbe693481c2db219cd268df7c30931bd0 500ea80ad47d99f774e88922c0ef2a610fe54b83c2248244208130d3951f109a d8059e61d2ef22940ec3c84994ce3eb27bb927d9f88fa8b067dc9064be8f3a5c ba8687abd052f886a2ffc0d211ebe07ce579b9e2fd3a5108cd04331e4c45b9cf], want 
[89e6d7b84cc416762a41b416cccde730579b2cfde7be8ce3b6c99c37105e8abf 039da41553f86793f4149de008805bd949e5337ffbc75b240c853c810789f088 c9f29c0810898c61a03b7783a301f53eec23c1376dea4f2ffb517ae810e2ad3f 2a7efd4bf1da88fda98c281c97ad797322704f752708c228a653a05aebcf5d1c af38ce26182a06b0eec8ac956acb95c4f32f716764b3e6f5d52a7fd99a7bb5c2 4c559008a116e51952086184c79f437f645be707a4fe2b885a0c8b29e23101ad 40f091982b075cb12843a6b34f1442cd631d4242341f579397e5d5fd94808acd b701f71bee362f71eba01446935b619ff5b7d81de5f6af2bf41238c7e7d54c8f c36cf3328724f203bff31592a4e6e646227987f7a76592f8384308ff140b20ec 0184e8248b846e4f1e4d58e23e1784a8f86388d033dac807637f474eadab6e29 f9e32ae702a1166ae82794317301acfac30070658148f3ad6c2c8f37dd2f577d 53663ecf8c19459dcd2374a2c234941ae9b0bc7a2eb3030ecd0377e414607b43 35368e62eb6c3ed2706279f98ced41a960b4962b18391d1fc1b8e31a268e093d 6dfdce03e12ec3f37cb2ad5a0131741669b5aebab5fa52e1fa8299cc47af187c 137ffddb14f79c095c180249c55ae12fcf4744557ccb3b47a74ad5cc66540882 6e76765489bd313cbb6a00b6d643f84768bb397f0700ca93a4a42b37a0c1687c c380ad7a3e2ad61a670bf49fd0aef63f2854bf439aed1abcbdd12981f778b9ab cb40bbb3cc862c7ee287e43f3ffbadd32f3ecd4d7a886009a99e580959aadb7b 4821fadf8b319027d1ee5dadbb4303edbe693481c2db219cd268df7c30931bd0 869b277c5c0157b8aeed1ebb6c8c3b715606a3bd66029a3e510b5f72e4a416d3 500ea80ad47d99f774e88922c0ef2a610fe54b83c2248244208130d3951f109a bddf772ae51977ae67ed82cba161876914b384e5783135615f6d8b5259b0e588 8a60e3e4b0603833aa891ac429b2eb23cfebdc536115740aefd95ddaca693950 6ded19f3fe623f5ba6fa4b02d1bb5484b5bf963a861ac992e6283eb938673c82 712e855ab603fe12376fd24015ed77456580b5d4318b4f137748bd14a4b3d45b ab23bde4d295bdd0fd2b094345ee8741422bc293ef1a6f583b1e841b66c012a5 ee89234d7c5397d0b4ddcd7b65c454deb1886481286b032623d62b55df1a19e9 8f3f4ef4358c88d7c21fe8e81856fe26642ec8af9472b0175c7b13f71a921079 8366d3871a3e8ea81c20ed3c4fbc481f986fcf24f770209cd6e3242763854b6b 8e0ac2b5e4261ff83e396c1988a04752caf9fea067ab1e391eb51d4758567d2b e61d0ffdff3e77954a5581d532ba45621a9961c564b77905d4a0992acecbc44c c2d4eb02ac5f3f1cac5a3376ad037a2dead68d2a03b229ed7d4188e368079b49 b4537466075ac17f7a1d9d0a094f518d68730c35ea6f9a7fb30e4c894a816cb5 467bcc2cf2d7196d6386b5b0e58dd9666658059d741ae40c0239492b9ef0b6a4 b4a2b1d3a48568ec34f22a81b4443842ebbfab744dcfb0ca90d4eba6500ccab3 cbf8691c4d68210bffd39bf278416504a134172ab1e8e7d2c5349f066804eedc 82cb49c0e5af5dbfd7281494e21ad07d5b06b15e8b857fe1167a4bdee817b1a6 5efb98122f57546e576dd9183610ca210041f663572af95bdf635f3dc009c8ee d8059e61d2ef22940ec3c84994ce3eb27bb927d9f88fa8b067dc9064be8f3a5c ba8687abd052f886a2ffc0d211ebe07ce579b9e2fd3a5108cd04331e4c45b9cf]
=== RUN   TestBroadcastPeers/OK_-_multiple_batches_-_max_number_of_records
--- FAIL: TestBroadcastPeers (22.50s)
    --- PASS: TestBroadcastPeers/OK_-_single_record (0.10s)
    --- PASS: TestBroadcastPeers/OK_-_single_batch_-_multiple_records (0.92s)
    --- FAIL: TestBroadcastPeers/OK_-_single_batch_-_max_number_of_records (1.76s)
    --- FAIL: TestBroadcastPeers/OK_-_multiple_batches (2.09s)
    --- PASS: TestBroadcastPeers/OK_-_multiple_batches_-_max_number_of_records (2.05s)
FAIL
FAIL	github.com/ethersphere/bee/pkg/hive	23.182s
?   	github.com/ethersphere/bee/pkg/hive/pb	[no test files]

**Comment by acud** [comment] 2020-07-28 16:31
duplicate of #485

**Closed by acud** 2020-07-28 16:31 UTC
Labels: bug
