### ISSUE TITLE
http: panic serving 127.0.0.1:58978: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Baleba** [ethersphere/bee#829] opened 2020-10-10 11:58 UTC
Hi there,

was trying to upload a 5.5Mb  video file. 

**My configuration:**

raspberry pi 4 
Linux ubuntu 5.8.0+ #1 SMP PREEMPT Fri Sep 25 22:26:37 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

**bee version**

```
ubuntu@ubuntu:~/.local$ bee version
0.3.2-9d7d98f

```

**upload console**

```
ubuntu@ubuntu:/mnt/beecachefs/ubuntu/Videos/BlickBassy$ curl -F file=@'BLICK BASSY   NLAL.m4a' http://localhost:8080/files
curl: (52) Empty reply from server
```
got the above on the upload console and the errors below on the bee console. Checked memory, there doesn't seem to be a problem with memory.

**Memory conf:**

```
ubuntu@ubuntu:~/.local$ free -h
              total        used        free      shared  buff/cache   available
Mem:          1.8Gi       647Mi       308Mi       0.0Ki       892Mi       1.2Gi
Swap:         2.0Gi        62Mi       1.9Gi
```
**bee console**

```
ERRO[2020-10-10T11:30:21Z] http: panic serving 127.0.0.1:58978: runtime error: invalid memory address or nil pointer dereference 
ERRO[2020-10-10T11:30:21Z] goroutine 22502 [running]:                   
ERRO[2020-10-10T11:30:21Z] net/http.(*conn).serve.func1(0x40020d8fa0)   
ERRO[2020-10-10T11:30:21Z] 	net/http/server.go:1801 +0xfc               
ERRO[2020-10-10T11:30:21Z] panic(0xcfc340, 0x1a8bb50)                   
ERRO[2020-10-10T11:30:21Z] 	runtime/panic.go:975 +0x370                 
ERRO[2020-10-10T11:30:21Z] math/big.(*Int).Mul(0x400188c638, 0x0, 0x400188c738, 0x0) 
ERRO[2020-10-10T11:30:21Z] 	math/big/int.go:168 +0xcc                   
ERRO[2020-10-10T11:30:21Z] github.com/btcsuite/btcd/btcec.recoverKeyFromSignature(0x1ac41a0, 0x400188c728, 0x4002616280, 0x20, 0x20, 0x2, 0x40033b1700, 0x1, 0x8, 0x70af14) 
ERRO[2020-10-10T11:30:21Z] 	github.com/btcsuite/btcd@v0.20.1-beta/btcec/signature.go:322 +0x1ac 
ERRO[2020-10-10T11:30:21Z] github.com/btcsuite/btcd/btcec.RecoverCompact(0x1ac41a0, 0x400188c7f8, 0x41, 0x41, 0x4002616280, 0x20, 0x20, 0x0, 0x400188c848, 0xb98d00, ...) 
ERRO[2020-10-10T11:30:21Z] 	github.com/btcsuite/btcd@v0.20.1-beta/btcec/signature.go:413 +0x19c 
ERRO[2020-10-10T11:30:21Z] github.com/ethersphere/bee/pkg/crypto.Recover(0x4003f44c20, 0x41, 0xfe8, 0x4002616240, 0x20, 0x20, 0x20, 0x400230e660, 0x11cfe00) 
ERRO[2020-10-10T11:30:21Z] 	github.com/ethersphere/bee/pkg/crypto/signer.go:61 +0xe0 
ERRO[2020-10-10T11:30:21Z] github.com/ethersphere/bee/pkg/soc.recoverAddress(0x4003f44c20, 0x41, 0xfe8, 0x4002616240, 0x20, 0x20, 0x4002616240, 0x20, 0x20, 0x0, ...) 
ERRO[2020-10-10T11:30:21Z] 	github.com/ethersphere/bee/pkg/soc/soc.go:225 +0x50 
ERRO[2020-10-10T11:30:21Z] github.com/ethersphere/bee/pkg/soc.FromChunk(0x11d6120, 0x4005947580, 0x40025a4940, 0x0, 0x0) 
ERRO[2020-10-10T11:30:21Z] 	github.com/ethersphere/bee/pkg/soc/soc.go:145 +0x1a4 
ERRO[2020-10-10T11:30:21Z] github.com/ethersphere/bee/pkg/soc.(*Validator).Validate(0x1af9ee0, 0x11d6120, 0x4005947580, 0x0) 
ERRO[2020-10-10T11:30:21Z] 	github.com/ethersphere/bee/pkg/soc/validator.go:24 +0x30 
ERRO[2020-10-10T11:30:21Z] github.com/ethersphere/bee/pkg/swarm.(*chunkValidator).Validate(0x40004ee5d0, 0x11d6120, 0x4005947580, 0x40025a4920) 
ERRO[2020-10-10T11:30:21Z] 	github.com/ethersphere/bee/pkg/swarm/swarm.go:180 +0x78 
ERRO[2020-10-10T11:30:21Z] github.com/ethersphere/bee/pkg/netstore.(*store).Put(0x4000aac140, 0x11cc140, 0x4003b4e7b0, 0x2, 0x40035baaf0, 0x1, 0x1, 0x400188cb78, 0x2, 0x2, ...) 
ERRO[2020-10-10T11:30:21Z] 	github.com/ethersphere/bee/pkg/netstore/netstore.go:79 +0x74 
ERRO[2020-10-10T11:30:21Z] github.com/ethersphere/bee/pkg/file/pipeline/store.(*storeWriter).ChainWrite(0x4003aaf840, 0x40033c1b00, 0x0, 0x0) 
ERRO[2020-10-10T11:30:21Z] 	github.com/ethersphere/bee/pkg/file/pipeline/store/store.go:49 +0x21c 
ERRO[2020-10-10T11:30:21Z] github.com/ethersphere/bee/pkg/file/pipeline/bmt.(*bmtWriter).ChainWrite(0x40003d2a20, 0x40033c1b00, 0x1000, 0x4003f44c00) 
ERRO[2020-10-10T11:30:21Z] 	github.com/ethersphere/bee/pkg/file/pipeline/bmt/bmt.go:52 +0x154 
ERRO[2020-10-10T11:30:21Z] github.com/ethersphere/bee/pkg/file/pipeline/feeder.(*chunkFeeder).Write(0x4003aaf900, 0x40012bb000, 0x1000, 0x1000, 0x1000, 0x0, 0x0) 
ERRO[2020-10-10T11:30:21Z] 	github.com/ethersphere/bee/pkg/file/pipeline/feeder/feeder.go:78 +0x294 
ERRO[2020-10-10T11:30:21Z] github.com/ethersphere/bee/pkg/file/pipeline/builder.FeedPipeline(0x11cc140, 0x4003b4e7b0, 0x11b9a40, 0x4003aaf900, 0x11ab700, 0x4005076720, 0x548bbe, 0x4003aaf900, 0x0, 0x0, ...) 
ERRO[2020-10-10T11:30:21Z] 	github.com/ethersphere/bee/pkg/file/pipeline/builder/builder.go:100 +0xc8 
ERRO[2020-10-10T11:30:21Z] github.com/ethersphere/bee/pkg/api.(*server).fileUploadHandler(0x40004ff520, 0x11c3800, 0x4003b4e5a0, 0x4004738900) 
ERRO[2020-10-10T11:30:21Z] 	github.com/ethersphere/bee/pkg/api/file.go:157 +0x550 
ERRO[2020-10-10T11:30:21Z] net/http.HandlerFunc.ServeHTTP(0x4000668490, 0x11c3800, 0x4003b4e5a0, 0x4004738900) 
ERRO[2020-10-10T11:30:21Z] 	net/http/server.go:2042 +0x40               
ERRO[2020-10-10T11:30:21Z] github.com/ethersphere/bee/pkg/api.(*server).newTracingHandler.func1.1(0x11c3800, 0x4003b4e5a0, 0x4004738800) 
ERRO[2020-10-10T11:30:21Z] 	github.com/ethersphere/bee/pkg/api/api.go:189 +0x178 
ERRO[2020-10-10T11:30:21Z] net/http.HandlerFunc.ServeHTTP(0x40004eebd0, 0x11c3800, 0x4003b4e5a0, 0x4004738800) 
ERRO[2020-10-10T11:30:21Z] 	net/http/server.go:2042 +0x40               
ERRO[2020-10-10T11:30:21Z] resenje.org/web.HandleMethods(0x40004eeba0, 0xef47f6, 0x2b, 0xede910, 0x1f, 0x11c3800, 0x4003b4e5a0, 0x4004738800) 
ERRO[2020-10-10T11:30:21Z] 	resenje.org/web@v0.4.3/method.go:20 +0x4d4  
ERRO[2020-10-10T11:30:21Z] github.com/ethersphere/bee/pkg/jsonhttp.MethodHandler.ServeHTTP(0x40004eeba0, 0x11c3800, 0x4003b4e5a0, 0x4004738800) 
ERRO[2020-10-10T11:30:21Z] 	github.com/ethersphere/bee/pkg/jsonhttp/handlers.go:16 +0x74 
ERRO[2020-10-10T11:30:21Z] github.com/gorilla/mux.(*Router).ServeHTTP(0x40007180c0, 0x11c3800, 0x4003b4e5a0, 0x4004738600) 
ERRO[2020-10-10T11:30:21Z] 	github.com/gorilla/mux@v1.7.4/mux.go:210 +0x9c 
ERRO[2020-10-10T11:30:21Z] github.com/ethersphere/bee/pkg/api.(*server).gatewayModeForbidHeadersHandler.func1(0x11c3800, 0x4003b4e5a0, 0x4004738600) 
ERRO[2020-10-10T11:30:21Z] 	github.com/ethersphere/bee/pkg/api/router.go:194 +0x54 
ERRO[2020-10-10T11:30:21Z] net/http.HandlerFunc.ServeHTTP(0x400000c800, 0x11c3800, 0x4003b4e5a0, 0x4004738600) 
ERRO[2020-10-10T11:30:21Z] 	net/http/server.go:2042 +0x40               
ERRO[2020-10-10T11:30:21Z] github.com/ethersphere/bee/pkg/api.(*server).setupRouting.func5.1(0x11c3800, 0x4003b4e5a0, 0x4004738600) 
ERRO[2020-10-10T11:30:21Z] 	github.com/ethersphere/bee/pkg/api/router.go:152 +0xb4 
ERRO[2020-10-10T11:30:21Z] net/http.HandlerFunc.ServeHTTP(0x400000c840, 0x11c3800, 0x4003b4e5a0, 0x4004738600) 
ERRO[2020-10-10T11:30:21Z] 	net/http/server.go:2042 +0x40               
ERRO[2020-10-10T11:30:21Z] github.com/ethersphere/bee/pkg/api.(*server).pageviewMetricsHandler.func1(0x11c3800, 0x4003b4e5a0, 0x4004738600) 
ERRO[2020-10-10T11:30:21Z] 	github.com/ethersphere/bee/pkg/api/metrics.go:52 +0x94 
ERRO[2020-10-10T11:30:21Z] net/http.HandlerFunc.ServeHTTP(0x400000c880, 0x11c3800, 0x4003b4e5a0, 0x4004738600) 
ERRO[2020-10-10T11:30:21Z] 	net/http/server.go:2042 +0x40               
ERRO[2020-10-10T11:30:21Z] github.com/gorilla/handlers.CompressHandlerLevel.func1(0x11c3800, 0x4003b4e5a0, 0x4004738600) 
ERRO[2020-10-10T11:30:21Z] 	github.com/gorilla/handlers@v1.4.2/compress.go:148 +0x140 
ERRO[2020-10-10T11:30:21Z] net/http.HandlerFunc.ServeHTTP(0x400000c8c0, 0x11c3800, 0x4003b4e5a0, 0x4004738600) 
ERRO[2020-10-10T11:30:21Z] 	net/http/server.go:2042 +0x40               
ERRO[2020-10-10T11:30:21Z] github.com/ethersphere/bee/pkg/logging.NewHTTPAccessLogHandler.func1.1(0x11c6d80, 0x4000180380, 0x4004738600) 
ERRO[2020-10-10T11:30:21Z] 	github.com/ethersphere/bee/pkg/logging/http_access.go:24 +0xe0 
ERRO[2020-10-10T11:30:21Z] net/http.HandlerFunc.ServeHTTP(0x40009e6a80, 0x11c6d80, 0x4000180380, 0x4004738600) 
ERRO[2020-10-10T11:30:21Z] 	net/http/server.go:2042 +0x40               
ERRO[2020-10-10T11:30:21Z] net/http.serverHandler.ServeHTTP(0x40008b4380, 0x11c6d80, 0x4000180380, 0x4004738600) 
ERRO[2020-10-10T11:30:21Z] 	net/http/server.go:2843 +0xbc               
ERRO[2020-10-10T11:30:21Z] net/http.(*conn).serve(0x40020d8fa0, 0x11cc080, 0x4003b2b280) 
ERRO[2020-10-10T11:30:21Z] 	net/http/server.go:1925 +0x6f4              
ERRO[2020-10-10T11:30:21Z] created by net/http.(*Server).Serve          
ERRO[2020-10-10T11:30:21Z] 	net/http/server.go:2969 +0x2e8              
WARN[2020-10-10T11:31:19Z] connecting to peer [Overlay: 86654bc7ff190b9e913f6eafdaa35181d9809484ce4daddf91b1a50331241c58, Underlay: /ip4/10.0.215.142/tcp/31003/p2p/16Uiu2HAmFjLgmUNhwsUabUrKEQqSkifBVgAjGjSYRppTTCTJPZG2]: context deadline exceeded 
```

**Comment by acud** [comment] 2020-10-11 10:35
@Baleba could you kindly provide the CLI arguments you used to start `bee` with?

**Comment by Baleba** [comment] 2020-10-11 10:40
bee start --config /home/ubuntu/config/bee-config.yaml

ubuntu@ubuntu:/mnt/beecachefs/ubuntu/.bee/localstore$ cat /home/ubuntu/config/bee-config.yaml 

api-addr: pi4bee:8080
bootnode:
- /dnsaddr/bootnode.ethswarm.org
clef-signer-enable: false
clef-signer-endpoint: ""
config: /home/ubuntu/config/bee-config.yaml
cors-allowed-origins: []
data-dir: /mnt/beecachefs/ubuntu/.bee
db-capacity: "100000000"
debug-api-addr: :6060
debug-api-enable: true
gateway-mode: true
global-pinning-enable: true
help: false
nat-addr: ""
network-id: "1"
p2p-addr: :7070
p2p-quic-enable: false
p2p-ws-enable: false
password: ""
password-file: "/home/ubuntu/config/passwd.txt"
payment-early: "10000"
payment-threshold: "100000"
payment-tolerance: "10000"
resolver-options: []
standalone: false
swap-enable: true
swap-endpoint: https://goerli.infura.io/v3/95663375ebec47df9ae64514e6e6a040
swap-factory-address: ""
swap-initial-deposit: "100000000"
tracing-enable: false
tracing-endpoint: 127.0.0.1:6831
tracing-service-name: bee
verbosity: info
welcome-message: "Let's bee together"

**Comment by Baleba** [comment] 2020-10-11 10:54
It looks like a problem with that specific file, as I could upload other files, smaller and bigger.

**Comment by Eknir** [comment] 2020-10-13 11:29
@acud , I see that you merged 833 which referenced this issue. @janos mentioned that it doesn't fix the core problem, but it makes it (much?) less likely to appear. 

I would suggest to close this issue in favor of an issue which highlights the core problem. @janos , as you mentioned in #833 that the core problem is not fixed, could you please be so kind to make an issue, highlighting the core problem, so we can prioritize this accordingly?

@Baleba, would you be so kind to build master and see if the issue is resolved for you?

**Comment by janos** [comment] 2020-10-13 11:52
The core problem is much lower in the stack in dependencies. btcd RecoverCompact ends up with nil absolute values of bigints, which is a panic. We are passing a certain data that triggers it, but never nil values to crypto.Recover. Currently, I see no relation to the arm architecture, but it is an important information.

@Baleba could you provide the exact file size in bytes? Or even better the file itself if it is possible?

**Comment by acud** [comment] 2020-10-13 12:30
Also would be nice to know, if the exact same file fails on a normal `amd64` architecture in the same manner

**Comment by Baleba** [comment] 2020-10-13 19:37
[BLICK-BASSY-NLAL.m4a.gz](https://github.com/ethersphere/bee/files/5373715/BLICK-BASSY-NLAL.m4a.gz)
Here is the file.

**Comment by Baleba** [comment] 2020-10-13 19:57
@acud do you still need a test on normal `amd64` ? If so I need to do the test with the previous binary. Let me know.

**Comment by janos** [comment] 2020-10-14 08:21
@Baleba thank you for the file, I can confirm that the problem is reproducible on amd64 arch with 9d7d98f.

**Comment by janos** [comment] 2020-10-14 10:00
Issue is submitted upstream https://github.com/btcsuite/btcd/issues/1651.

For now, we can relay that this is much less likely to happen as SOC Validator is called after the content addressed chunk Validator.

**Comment by zelig** [comment] 2020-10-18 00:13
@janos this is not exactly reassuring wrt the chosen  dependency, esp that there is no reaction to the issue...

**Comment by janos** [comment] 2020-10-19 08:15
@zelig btcec package is used by many other projects (1k+) and it is very nicely written. I would give some more time for authors to respond.

**Comment by Baleba** [comment] 2020-11-13 10:26
Hi @janos Any news from the btcec guys? Can't see any change on the ticket you logged.

**Comment by janos** [comment] 2020-11-13 11:52
Hi @Baleba, unfortunately, we got no response from the btcec guys. The issue on the swarm side was not detected, but mainly as the soc validator was not called on arbitrary data. We may consider using a different btcec implementation, maybe even considering something that require cgo.

**Comment by Baleba** [comment] 2020-11-13 12:03
Ok, thanks.

**Comment by Eknir** [comment] 2021-01-28 13:54
I just send an email to one of the maintainers of this `btcd`.

**Comment by Eknir** [comment] 2021-05-31 16:44
I was in touch with the `btcd` guys a while ago, and they promised me they will fix it.

**Comment by Baleba** [comment] 2021-05-31 17:00
Really? Maybe we should have them on Gitcoin and fund them. They don't sound like they have any incentive to work on this issue. Imagine we have a major bug after V1? This is just too slow. Good you guys found a workaround.
Anyway, better late than never. Wait and see. 

Thank for the update.

**Closed** 2021-07-09 05:56 UTC
Labels: bug

**Comment by acud** [comment] 2021-07-09 06:06
This should be addressed by the updated version that's been committed into `bee` in #2316
