### ISSUE TITLE
pullstorage test erro in CI

### ISSUE THREAD

**Issue by jmozah** [ethersphere/bee#545] opened 2020-08-07 13:05 UTC
In chuk-repair branch,  macos, race test 
https://github.com/ethersphere/bee/pull/479/checks?check_run_id=958294738

##[error]    pullstorage_test.go:147: want 2 addrs but got 5

```
=== RUN   TestIntervalChunks_NoChunksLater
Error:     pullstorage_test.go:147: want 2 addrs but got 5
--- FAIL: TestIntervalChunks_NoChunksLater (0.60s)
=== RUN   TestIntervalChunks_Blocking
```

**Comment by acud** [comment] 2020-10-08 10:12
can't reproduce this locally. @janos maybe you would have more luck than me?

**Comment by Eknir** [comment] 2020-10-13 11:09
@janos @acud , let's try to reproduce and close if it is not reproducable.

**Comment by Eknir** [comment] 2020-10-27 16:15
Closing this issue, as it cannot be reproduced. Thanks for attempt @acud !

**Closed by Eknir** 2020-10-27 16:15 UTC
Labels: flaky-test
