### ISSUE TITLE
More available than total balance?

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1496] opened 2021-03-25 18:12 UTC
#### Summary
I have no idea how it happened, but a person I was supporting (Javaer) has a checkbook balance that is less than the available balance:

{
  "totalBalance": 104140332000000000,
  "availableBalance": 104168003000000000
}

#### Steps to reproduce
No idea, sorry.

#### Expected behavior
I would expect the available to always be less than or equal to the total?

#### Actual behavior
As you can see above, this checkbook claims to have more available than it's own balance.  Oh, and no settlements have occurred on this newly deployed node.

**Comment by Eknir** [comment] 2021-04-13 09:03
This is interesting, but because it cannot be reproduced, I will close this issue now. Please reopen it if it can be reproduced, or this is some more information available that will point us in the right direction.

**Closed by Eknir** 2021-04-13 09:03 UTC
Labels: bug, issue
