### ISSUE TITLE
【BUG Crash】panic: runtime error: index out of range [16] with length 16

### ISSUE THREAD

**Issue by cppfuns** [ethersphere/bee#1837] opened 2021-05-22 11:50 UTC
```
time="2021-05-22T19:47:47+08:00" level=warning msg="cannot continue until there is sufficient ETH (for Gas) available on ad256b983bc08ea4b61669c89adb21835abb3475"
time="2021-05-22T19:47:47+08:00" level=warning msg="get your Goerli ETH and Goerli BZZ now via the bzzaar at https://bzz.ethswarm.org/?transaction=buy&amount=1&slippage=30&receiver=0xad256b983bc08ea4b61669c89adb21835abb3475"
time="2021-05-22T19:48:07+08:00" level=warning msg="cannot continue until there is sufficient ETH (for Gas) available on ad256b983bc08ea4b61669c89adb21835abb3475"
time="2021-05-22T19:48:07+08:00" level=warning msg="get your Goerli ETH and Goerli BZZ now via the bzzaar at https://bzz.ethswarm.org/?transaction=buy&amount=1&slippage=30&receiver=0xad256b983bc08ea4b61669c89adb21835abb3475"
time="2021-05-22T19:48:28+08:00" level=trace msg="sending transaction 1deedf9c702ff491daf6487a5ac3043cfb14bb91bd7d852a8a966453f6ac3a7f with nonce 0"
time="2021-05-22T19:48:28+08:00" level=info msg="deploying new chequebook in transaction 1deedf9c702ff491daf6487a5ac3043cfb14bb91bd7d852a8a966453f6ac3a7f"
time="2021-05-22T19:48:28+08:00" level=trace msg="starting to watch transaction 1deedf9c702ff491daf6487a5ac3043cfb14bb91bd7d852a8a966453f6ac3a7f with nonce 0"
time="2021-05-22T19:48:43+08:00" level=info msg="deployed chequebook at address 1e2c48165bdda96724ccfa7e28594f6967e0c343"
time="2021-05-22T19:48:43+08:00" level=info msg="depositing 10000000000000000 token into new chequebook"
time="2021-05-22T19:48:43+08:00" level=trace msg="sending transaction 7c704407dd4c7626cd71ed763534992a49827100516828f8e53d7a89425b5a0a with nonce 1"
time="2021-05-22T19:48:43+08:00" level=info msg="sent deposit transaction 7c704407dd4c7626cd71ed763534992a49827100516828f8e53d7a89425b5a0a"
time="2021-05-22T19:48:43+08:00" level=trace msg="starting to watch transaction 7c704407dd4c7626cd71ed763534992a49827100516828f8e53d7a89425b5a0a with nonce 1"
time="2021-05-22T19:48:58+08:00" level=info msg="successfully deposited to chequebook"
time="2021-05-22T19:48:58+08:00" level=info msg="using the chequebook transaction hash 1deedf9c702ff491daf6487a5ac3043cfb14bb91bd7d852a8a966453f6ac3a7f"
time="2021-05-22T19:48:58+08:00" level=info msg="using datadir in: './data/node1'"
time="2021-05-22T19:48:58+08:00" level=info msg="database capacity: 1000000 chunks (approximately 20.3GB)"
time="2021-05-22T19:48:58+08:00" level=debug msg="initializing NAT manager"
time="2021-05-22T19:49:11+08:00" level=debug msg="NAT manager initialized"
time="2021-05-22T19:49:11+08:00" level=info msg="waiting to sync postage contract data, this may take a while... more info available in Debug loglevel"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated block height to 4819123"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated chain price to 1"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated block height to 4819245"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: created batch id cb34d9bf3d088ef5530455b5164df5bcc715c96b41aa73a12b2cbd792f3eaff4"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated block height to 4819259"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: created batch id f1d89909e2fde297d7a4d578b6549952aacf5c25ef8883d8f4b170a36ac75f71"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated block height to 4819285"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: created batch id ccd5b87c4e9f3ba0b6d62dbbcec7ce3ad474ccd8877f4acaa36507d2d255b643"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated block height to 4819298"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: created batch id b7b7737d93a043e075f236f01b81e9a89fecf388fa116cd79205d69aa3de9fd9"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated block height to 4819304"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: created batch id 1311a4ac94c6fd0e14f14666081de3787c6dd4205d7f882b873f054e8a3b367d"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated block height to 4819322"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: created batch id 7ff31be685931e7e5837828892587300a3fb6565a96ad4415b4dbecd8e0fb564"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated block height to 4819355"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: created batch id 9dd106465a85f1220034bbf1f0113526f69d129c6a5ffaafad2c984417901e1f"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated block height to 4819376"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: created batch id d72d1a2aec97fd564d9faae3b52ea819826cda96f50fb0fcf7e763c5f6ab7cc8"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated block height to 4820073"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: created batch id ab15d7dec8b99e1e10ae51fe54b56bd6f2106d790651e5ddd39fce051485a22b"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated block height to 4823980"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated block height to 4828981"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated block height to 4829823"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: created batch id 07b2f766324dfb3054e6c4934cd624f78135b6ac7c9c840d4cf40bf02b593aae"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated block height to 4830238"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: created batch id 4d4ab39bef3347200521682e83f30525526e5ca0e008371f870b6df8ea576d57"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated block height to 4830265"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: created batch id b998cd3a1eabfbeec53655945574c4461aefcb3d87f207ef0c462cbf5657035f"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated block height to 4830590"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: created batch id 310ed0ca9cf209c0653e936b34212dc5ac475a3a3ddef4fca96eb769a01e9173"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated block height to 4832597"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: created batch id 073a5eba7b4105969ae662c7792feeee83c99fbb183c7a7e10e5d31a7b081614"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated block height to 4833982"
time="2021-05-22T19:49:11+08:00" level=debug msg="p2p address: /ip4/172.18.0.100/tcp/1634/p2p/16Uiu2HAmKFVrBFoFBD4vUkFwmeuFjXz2dKmPxxbsT5PpS9Hx2yWW"
time="2021-05-22T19:49:11+08:00" level=debug msg="p2p address: /ip4/127.0.0.1/tcp/1634/p2p/16Uiu2HAmKFVrBFoFBD4vUkFwmeuFjXz2dKmPxxbsT5PpS9Hx2yWW"
time="2021-05-22T19:49:11+08:00" level=debug msg="p2p address: /ip6/::1/tcp/1634/p2p/16Uiu2HAmKFVrBFoFBD4vUkFwmeuFjXz2dKmPxxbsT5PpS9Hx2yWW"
time="2021-05-22T19:49:11+08:00" level=info msg="starting in full mode"
time="2021-05-22T19:49:11+08:00" level=info msg="name resolver: no name resolution service provided"
time="2021-05-22T19:49:11+08:00" level=info msg="api address: [::]:1633"
time="2021-05-22T19:49:11+08:00" level=trace msg="kademlia: connector took 5.448µs to finish: old depth 0; new depth 0"
time="2021-05-22T19:49:11+08:00" level=debug msg="kademlia: no connected peers, trying bootnodes"
time="2021-05-22T19:49:11+08:00" level=trace msg="connecting to bootnode /ip4/52.90.206.204/tcp/31309/p2p/16Uiu2HAmLe8hu7N9cnkY4BjwjtdfsPzYLoebk5rUbHsiYKvMpBHW"
time="2021-05-22T19:49:11+08:00" level=debug msg="batch service: updated block height to 4835778"
time="2021-05-22T19:49:11+08:00" level=trace msg="handshake finished for peer (outbound) 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8"
time="2021-05-22T19:49:11+08:00" level=info msg="greeting \"Welcome to the Swarm, you are Bee-ing connected!\" from peer: 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8"
time="2021-05-22T19:49:11+08:00" level=trace msg="received payment threshold announcement from peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 of 10000000000000"
time="2021-05-22T19:49:11+08:00" level=trace msg="sending payment threshold announcement to peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 of 10000000000000"
time="2021-05-22T19:49:11+08:00" level=trace msg="initial swap handshake peer: 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 beneficiary: 087db473170e9564a4daa5b96d3391843c9420ec"
time="2021-05-22T19:49:11+08:00" level=debug msg="successfully connected to peer [Overlay: 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8, Underlay: /ip4/52.90.206.204/tcp/31309/p2p/16Uiu2HAmLe8hu7N9cnkY4BjwjtdfsPzYLoebk5rUbHsiYKvMpBHW] (outbound)"
time="2021-05-22T19:49:11+08:00" level=info msg="successfully connected to peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 (outbound)"
time="2021-05-22T19:49:11+08:00" level=trace msg="connected to bootnode /ip4/52.90.206.204/tcp/31309/p2p/16Uiu2HAmLe8hu7N9cnkY4BjwjtdfsPzYLoebk5rUbHsiYKvMpBHW"
time="2021-05-22T19:49:11+08:00" level=trace msg="connecting to bootnode /ip4/54.210.29.30/tcp/31308/p2p/16Uiu2HAmRHY7h1cdpmB6S48MGfwecG3kfhLT9cXpE8SokS9o1Cck"
time="2021-05-22T19:49:11+08:00" level=trace msg="handshake finished for peer (outbound) b4e5df012cfc281e74bb517fcf87fc2c07cd787929c332fc805f8124401fabae"
time="2021-05-22T19:49:11+08:00" level=info msg="greeting \"Welcome to the Swarm, you are Bee-ing connected!\" from peer: b4e5df012cfc281e74bb517fcf87fc2c07cd787929c332fc805f8124401fabae"
time="2021-05-22T19:49:11+08:00" level=trace msg="received payment threshold announcement from peer b4e5df012cfc281e74bb517fcf87fc2c07cd787929c332fc805f8124401fabae of 10000000000000"
time="2021-05-22T19:49:11+08:00" level=trace msg="liveSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 15 cursor 0"
time="2021-05-22T19:49:11+08:00" level=trace msg="liveSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 3 cursor 70"
time="2021-05-22T19:49:11+08:00" level=trace msg="liveSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 2 cursor 94"
time="2021-05-22T19:49:11+08:00" level=trace msg="liveSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 11 cursor 1"
time="2021-05-22T19:49:11+08:00" level=trace msg="liveSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 13 cursor 0"
time="2021-05-22T19:49:11+08:00" level=trace msg="liveSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 12 cursor 0"
time="2021-05-22T19:49:11+08:00" level=trace msg="liveSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 10 cursor 1"
time="2021-05-22T19:49:11+08:00" level=trace msg="histSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 3 cursor 70"
time="2021-05-22T19:49:11+08:00" level=trace msg="liveSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 9 cursor 0"
time="2021-05-22T19:49:11+08:00" level=trace msg="histSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 10 cursor 1"
time="2021-05-22T19:49:11+08:00" level=trace msg="liveSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 6 cursor 10"
time="2021-05-22T19:49:11+08:00" level=trace msg="liveSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 4 cursor 44"
time="2021-05-22T19:49:11+08:00" level=trace msg="histSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 4 cursor 44"
time="2021-05-22T19:49:11+08:00" level=trace msg="histSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 6 cursor 10"
time="2021-05-22T19:49:11+08:00" level=trace msg="histSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 7 cursor 9"
time="2021-05-22T19:49:11+08:00" level=trace msg="liveSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 7 cursor 9"
time="2021-05-22T19:49:11+08:00" level=trace msg="histSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 11 cursor 1"
time="2021-05-22T19:49:11+08:00" level=trace msg="liveSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 8 cursor 0"
time="2021-05-22T19:49:11+08:00" level=trace msg="histSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 5 cursor 19"
time="2021-05-22T19:49:11+08:00" level=trace msg="liveSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 5 cursor 19"
time="2021-05-22T19:49:11+08:00" level=trace msg="histSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 1 cursor 375"
time="2021-05-22T19:49:11+08:00" level=trace msg="liveSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 1 cursor 375"
time="2021-05-22T19:49:11+08:00" level=trace msg="liveSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 14 cursor 0"
time="2021-05-22T19:49:11+08:00" level=trace msg="histSyncWorker starting, peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 bin 2 cursor 94"
time="2021-05-22T19:49:11+08:00" level=trace msg="sending payment threshold announcement to peer b4e5df012cfc281e74bb517fcf87fc2c07cd787929c332fc805f8124401fabae of 10000000000000"
time="2021-05-22T19:49:11+08:00" level=trace msg="initial swap handshake peer: b4e5df012cfc281e74bb517fcf87fc2c07cd787929c332fc805f8124401fabae beneficiary: 2e25103bf91b0952e6e8075ad3011e91361196e8"
time="2021-05-22T19:49:11+08:00" level=debug msg="successfully connected to peer [Overlay: b4e5df012cfc281e74bb517fcf87fc2c07cd787929c332fc805f8124401fabae, Underlay: /ip4/54.210.29.30/tcp/31308/p2p/16Uiu2HAmRHY7h1cdpmB6S48MGfwecG3kfhLT9cXpE8SokS9o1Cck] (outbound)"
time="2021-05-22T19:49:11+08:00" level=info msg="successfully connected to peer b4e5df012cfc281e74bb517fcf87fc2c07cd787929c332fc805f8124401fabae (outbound)"
time="2021-05-22T19:49:11+08:00" level=trace msg="connected to bootnode /ip4/54.210.29.30/tcp/31308/p2p/16Uiu2HAmRHY7h1cdpmB6S48MGfwecG3kfhLT9cXpE8SokS9o1Cck"
time="2021-05-22T19:49:11+08:00" level=trace msg="connecting to bootnode /ip4/100.26.242.174/tcp/31301/p2p/16Uiu2HAmHgthsmN99SDMaApv5XY2YaCLeU9gkrPWBzRWBCaLPphs"
time="2021-05-22T19:49:11+08:00" level=trace msg="handshake finished for peer (outbound) fdf53bb6dfc06daea4b8dbd9aa348533f6fbc5038f7f50a1ffdb950d133ac968"
time="2021-05-22T19:49:11+08:00" level=info msg="greeting \"Welcome to the Swarm, you are Bee-ing connected!\" from peer: fdf53bb6dfc06daea4b8dbd9aa348533f6fbc5038f7f50a1ffdb950d133ac968"
time="2021-05-22T19:49:11+08:00" level=debug msg="puller recalculating peer 339cf2ca75f154ffb8dd13de024c4a5c5b53827b8fd21f24bec05835e0cdc2e8 po 1 depth 0"
time="2021-05-22T19:49:11+08:00" level=trace msg="liveSyncWorker starting, peer b4e5df012cfc281e74bb517fcf87fc2c07cd787929c332fc805f8124401fabae bin 1 cursor 341"
panic: runtime error: index out of range [16] with length 16

goroutine 604 [running]:
github.com/ethersphere/bee/pkg/puller.(*Puller).recalcPeer(0xc0001fc0f0, 0x1893840, 0xc001199000, 0xc000e66440, 0x20, 0x20, 0xc0012a0001)
	github.com/ethersphere/bee/pkg/puller/puller.go:220 +0x67d
github.com/ethersphere/bee/pkg/puller.(*Puller).manage(0xc0001fc0f0)
	github.com/ethersphere/bee/pkg/puller/puller.go:170 +0x425
created by github.com/ethersphere/bee/pkg/puller.New
	github.com/ethersphere/bee/pkg/puller/puller.go:82 +0x2aa
```

**Comment by rogerlzp** [comment] 2021-05-22 12:11
get the same issue here.
![image](https://user-images.githubusercontent.com/1296316/119226037-e259d480-bb39-11eb-9f4a-17e08ac03b24.png)

**Comment by ldeffenb** [comment] 2021-05-22 13:22
Duplicate of #1823

**Closed** 2021-05-31 16:42 UTC
Labels: bug, issue
