### ISSUE TITLE
Wrongly concluding that I am the closest node when building up Kademlia

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1504] opened 2021-03-26 14:05 UTC
#### Summary
I had a node which was trying (and failing) to push a bunch of chunks to closest peers, possibly due to #1503 .  This node was retrying the pushes over and over again.  I restarted the node and saw the entire pending push queue dump to the first peer that was successfully connected.  I can only presume that the node had somehow different or better connections into the required destination neighborhood, but have no way to be certain.

#### Steps to reproduce
Build up a pusher retry queue in a node for whatever reason.  It may be #1503 or a bunch of non-responsive nodes causing "stream reset" or "context deadline exceeded", but for whatever reason, your node cannot deliver one or more chunks to its closest nodes.

Restart that node and you should see the entire queue of pending chunks be delivered through the first connected peer.

#### Expected behavior
If the chunks can be delivered after a restart, why aren't they able to be delivered before the restart?  Rather than continuously trying and failing the same set of 5 "closest" peers, should pusher retries retain the peers that were previously failed and try a different, or increasing, set of peers on subsequent push retries?

#### Actual behavior
Pusher tries over and over until the node restarts and then the chunks are delivered.

The full node --verbosity 5 log is at: https://pastebee.com/?f031416fcefd6082e5ae54a5c6d5e4a0eb139a9804f312cb2e84134c75301fe6

But here's the gist of it:
time="2021-03-26T08:33:37-04:00" level=info msg="version: 0.5.3-23baf60-dirty"
time="2021-03-26T08:33:37-04:00" level=warning msg="clef is not enabled; portability and security of your keys is sub optimal"
time="2021-03-26T08:33:38-04:00" level=info msg="using existing swarm network address: 978a4128246abb0283a440d21731f629e4cc59394decae2bb01679fcda879d6e"
time="2021-03-26T08:33:38-04:00" level=info msg="swarm public key 03faf2886ae088aba53ca7f8e6427842b9a2e5c2cfab0bafd71e05ca9e45137252"
time="2021-03-26T08:33:38-04:00" level=debug msg="using existing libp2p key"
time="2021-03-26T08:33:38-04:00" level=debug msg="using existing pss key"
time="2021-03-26T08:33:38-04:00" level=info msg="pss public key 02aeae9c39c66ed030e5c309fc1d1bd4c01b479c0c7cc1156662d7f24f07e5c22e"
time="2021-03-26T08:33:38-04:00" level=info msg="using ethereum address 4a096258e359ecfc3a2161a7be5ad147bbd0df49"
time="2021-03-26T08:33:38-04:00" level=info msg="debug api address: [::]:6060"
time="2021-03-26T08:33:38-04:00" level=info msg="using default factory address for chain id 5: f0277caffea72734853b834afc9892461ea18474"
time="2021-03-26T08:33:38-04:00" level=info msg="using existing chequebook f857237cbdcd01427d4d6eb610623a0bd0af35d3"
time="2021-03-26T08:33:39-04:00" level=debug msg="p2p address: /ip4/68.202.16.212/tcp/7070/p2p/16Uiu2HAmE15aiZMvXi3HV8TckP6BaYgNWeCxWwP8ywnqG4eYDJx4"
time="2021-03-26T08:33:39-04:00" level=info msg="database capacity: 5000000 chunks (approximately 19.5GB)"
time="2021-03-26T08:33:43-04:00" level=trace msg="pusher timer.C after -1 chunks in batch, 0 inflight"
time="2021-03-26T08:33:43-04:00" level=info msg="name resolver: no name resolution service provided"
time="2021-03-26T08:33:43-04:00" level=info msg="api address: [::]:8080"
time="2021-03-26T08:33:43-04:00" level=debug msg="pusher chunk 9467b36b72b85847410b896d3c3344194386ec7a08337f74006874e28dea33be err closest peer: no peer found"
time="2021-03-26T08:33:43-04:00" level=debug msg="pusher chunk 94655f56a7644395a6812a5c8344317df66d8dc8eb77a3210250b4a846c294f7 err closest peer: no peer found"
time="2021-03-26T08:33:43-04:00" level=debug msg="pusher chunk 9466463bd0a1d63ea29e94816caafc74bbc82065dc08b526556c431c9d7b480f err closest peer: no peer found"
time="2021-03-26T08:33:43-04:00" level=debug msg="pusher chunk 94665b315fc894f23e342cb950b6a302164afba2e7be677d8dd1845bb2d2c375 err closest peer: no peer found"
time="2021-03-26T08:33:43-04:00" level=debug msg="pusher chunk 94663b9e9de19e9bbb6617a363667ff6d3d677eaa09024a888d548af94cb45e8 err closest peer: no peer found"
time="2021-03-26T08:33:43-04:00" level=debug msg="pusher chunk 94658a7a71a1c5485277768a57c45258ea5738678e2a99c96bda4944d9c959db err closest peer: no peer found"
time="2021-03-26T08:33:43-04:00" level=debug msg="pusher chunk 94659adc7cce198ecc0de03ba051bf1fcd5409f3fb390e88b544b1b6237618a3 err closest peer: no peer found"

And it repeatedly runs through the entire pending queue with them all failing due to "no peer found" as it should.  A few connection attempts are made and failed, until:

time="2021-03-26T08:34:30-04:00" level=trace msg="handshake finished for peer (outbound) 13c76752769c97a03e29f78aa1f2accd6e1d613a22ef04bec4bfa173711f8ddf"
time="2021-03-26T08:34:30-04:00" level=trace msg="received payment threshold announcement from peer 13c76752769c97a03e29f78aa1f2accd6e1d613a22ef04bec4bfa173711f8ddf of 10000000000000"
time="2021-03-26T08:34:30-04:00" level=trace msg="initial swap handshake peer: 13c76752769c97a03e29f78aa1f2accd6e1d613a22ef04bec4bfa173711f8ddf beneficiary: 76e62c6d6cd231e0cc29c023f647a6cb9bbaca5e"
time="2021-03-26T08:34:31-04:00" level=trace msg="sending payment threshold announcement to peer 13c76752769c97a03e29f78aa1f2accd6e1d613a22ef04bec4bfa173711f8ddf of 10000000000000"
time="2021-03-26T08:34:31-04:00" level=debug msg="successfully connected to peer [Overlay: 13c76752769c97a03e29f78aa1f2accd6e1d613a22ef04bec4bfa173711f8ddf, Underlay: /ip4/178.170.49.26/tcp/1934/p2p/16Uiu2HAmFrn8LSwUN3sU8uDTM2CMTD8dGaELQREWKFJYuxGQMGR5] (outbound)"
time="2021-03-26T08:34:31-04:00" level=info msg="successfully connected to peer 13c76752769c97a03e29f78aa1f2accd6e1d613a22ef04bec4bfa173711f8ddf (outbound)"
time="2021-03-26T08:34:31-04:00" level=debug msg="kademlia:connected to peer: 13c76752769c97a03e29f78aa1f2accd6e1d613a22ef04bec4bfa173711f8ddf old depth: 0 new depth: 0"

So, we're only connected to 13c76752769c97a03e29f78aa1f2accd6e1d613a22ef04bec4bfa173711f8ddf from our node of 978a4128246abb0283a440d21731f629e4cc59394decae2bb01679fcda879d6e

And the next time the pusher wakes up - BOOM!  - The entire pending queue is pushed through that freshly connected peer.  And from the 2 peer IDs and the chunk IDs, I don't even think he's closer than my node, so I effectively pushed the chunks further away from my neighborhood to get them (supposedly) back closer than me in my own neighborhood?  But I didn't know that because my own neighborhood depth was still zero because I was still building up my connected peers.

time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 94655f56a7644395a6812a5c8344317df66d8dc8eb77a3210250b4a846c294f7"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 9467b36b72b85847410b896d3c3344194386ec7a08337f74006874e28dea33be"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 94665b315fc894f23e342cb950b6a302164afba2e7be677d8dd1845bb2d2c375"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 9466463bd0a1d63ea29e94816caafc74bbc82065dc08b526556c431c9d7b480f"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 94658a7a71a1c5485277768a57c45258ea5738678e2a99c96bda4944d9c959db"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 94663b9e9de19e9bbb6617a363667ff6d3d677eaa09024a888d548af94cb45e8"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 94665f45cfcd2186913aaba023b391988bdefb218c15964b971aad4fac47e618"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 94659adc7cce198ecc0de03ba051bf1fcd5409f3fb390e88b544b1b6237618a3"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 9466a824f65ae6cf3d01c9a9ced77e57c55d1031d460a359cf71602b3b538e97"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 94677eb60ff1e74742baef2040bbd66a3fa7aff8cee688f4acfe11a57d78a4c6"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 9464dc569260b88eb32ab676b9b2faa305b3e22acc1f9139d4c8fb627f8b0f1d"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 94653d198df7f67faa110b02e584abd1b1b2eebd4ab3a1721602381556a84a80"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 9466c5d016c56f022a385473ee9b83f715349c5544a698bf5e14c95d35327e8c"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 9466794188a02043a4493002b4bd45e2cc19a006927bf2d69bfffffbdee6d1dc"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 946537b98aeafcc6eb026f89c0858f7b901b2f1aee73228c540edf30216798b3"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 946434a939af04a1beab97a898a6ab2fb42038260ee04122a8ba8c2fce1426b6"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 94659d75f223d180d61d1c7bec7fa3c52e2ffdebfc4c5b03d7c254ddf2e561d7"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 946731199683dab68754ebc4f984d0847a6118e875ffa838511e5472440b073b"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 9466902b07417b8d100e1dbec075d555099a8eacb15d73cf2c16ccf397e1ea01"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 819dfa503907a89a662f6776945850223328303b3586a390534721ddf49caf20"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 9466e97d34b14d658cfc0765391cb6a77ccca92f87bd7099368d54f46067324d"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 8784b0d1facc686d26c17434d1a616853a0c7da915c8556d0b80182eb578e25a"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 9466d757d467c061431fcde09694949b46a64aab0d60be3e1b719921a2a91342"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 8624949fc1efe878d5a7dea55b8c6faf38aea8876e7ee06b4f8ffdfd1cd1da53"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 8621f1b874ff9c18e7a3688873dc9ee2f3af0e16ac2e21feeab9eab8e64c0cd2"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 82879c527e5b973a1fe10683186c4365a8c46091aea57bbb903e61b00ce5e5e2"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 8286f0f048454cb3f5dae484241dcd888455243e8286abca2c2dbcba5f525d6d"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 97b3c7a859e2b1bba764fb1e32f6f357e85c53af9ff43fee622d7b78a2643d8f"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 828583d813afc5f8dde63797e9c2d1d73e1110bb0bfd6e5cc9015a28bc8b645e"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 9464d4d5c21beec13d478bd61789bcc95a8b19fd0c957de366918ab517e5ad6e"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 8286dc546969787f53f9c9fba3af9af79cc44bcdfde73527581c77780fd636de"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 828039c8e2ff47415269b87578360c9983a210d7e7f7c6caed9b9eb2c5fabd79"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 9719d87c145afb8cc7beaf2ba6321025988730488eb7952cbf5bb5c574eb8c25"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 9708f47cca1b295bb08aa6f540e34a00edf80ac59ea5bcbbcc8cab834e9d2859"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 971e1b17795e7663853300c3a89351582e860b066b53c892f68850f80d4d4a78"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 9040c757de11c22b1d259db911e72cb4f86fb32fa53ed5b509b48af0e0ffb252"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 970c749d4b6df5134fbb2ec64b5a7823726bb9653843a320089bdf4d6269c735"
time="2021-03-26T08:34:35-04:00" level=debug msg="pusher pushed chunk 97b183c2f7822eacff139824ffbaadb3ccad37cda8c0cf97af1d11d916baed48"

**Comment by Eknir** [comment] 2021-04-13 08:36
Am I correct in assuming that this is not a bug on it's own, but it is an example of the retry logic in pusher being detrimental?

**Comment by ldeffenb** [comment] 2021-04-13 10:40
Actually, I've learned more about this since writing up this issue.  The actual problem lies in the interaction between the pusher, pushToClosest, and kademlia's ClosestPeer.

When the node was fully running, it had lots of connected peers and ClosestPeer always had more than 5 connected peers for every pending chunk that pushToClosest was given to exhaust the 5 retries causing a retry-able error to be returned to the pusher causing the infinite retries.

But immediately after the restart, there were no connected peers, which is fine because ClosestPeer returns topology.ErrNotFound which is still a retry-able error for the pusher.

But as soon as one peer is connected, ClosestPeer now returns topology.ErrWantSelf for every chunk where the retrying peer is closer than the single connected peer.  This error passes through pushToClosest and back to pusher who then invokes s.storer.Set(storage.ModeSetSync) which stops the retries and keeps the node in the localstore.

But these chunks are not really "close" to the node that has incorrectly decided to quit pushing and keep them.  Any subsequent retrieval requests are not likely to get to this node, and therefore those chunks will be effectively missing.

So it's not a problem that the pusher retry logic can fix, but it is caused by kademlia's ClosestPeer making a pre-mature return of topology.ErrWantSelf when it is still actively trying to build up the connectedPeers.

With the current implementation of pullsync, these chunks might eventually get out to where they belong in the swarm, but with the 0.6.0 changes to have pullsync only do the local neighborhood nodes, that recovery will be eliminated.

I have heard that there are also changes coming to pushsync, but since the puller has already removed these chunks from the pushindex, I can't see how such changes will recover them.

It seems that kademlia somehow needs to somehow detect that it is in a "startup" mode while actively building connectedPeers and attempting to increase the neighborhood depth and prevent ClosestPeer from prematurely returning topology.ErrWantSelf, but stick to topology.ErrNotFound for a while (seems arbitrary) or until it has determined that sufficient connections have been achieved (relative to the size of knownPeers and/or saturation?) or that the neighborhood depth has stabilized (whatever that means).  I'm hard-pressed to figure out something that works for both large and small swarms other than the consideration of connectedPeers vs knownPeers (1%?) or the depth stabilization (depth hasn't changed after N passes of manageC?).

But since this premature topology.ErrWantSelf also affects new chunks coming through via PushSync's handler, the fix needs to be in kademlia's ClosestPeer, and not just the pusher.  We don't want the node to prematurely conclude that it should keep a chunk when it is still new to the (changing) neighborhood.  Although new chunks coming through the handler might be covered by the "push to local neighborhood" for newly received chunks, and then hope that the single connected peer isn't also new and will properly forward the chunk?

**Comment by Eknir** [comment] 2021-04-13 12:14
Aha. Great detective work, and thanks for the writeup. This is indeed a problem and it will cause uploads to fail.

There are already two related issues:

- https://github.com/ethersphere/bee/issues/1437 makes any node in the forward chain to validate if the receipt was signed by a node from the neighborhood. We can then reject/retry if we got a receipt that did not come from the neighborhood.
- https://github.com/ethersphere/bee/issues/1243 defines the desire to differentiate between an aspiring full node and a full node, from the perspective of redundancy and being able to respond to forward requests. As I get now, it is not only that a syncing node can be delayed when responding to forward request, it can also misbehave.

**Comment by Eknir** [comment] 2021-04-13 12:17
I updated the title to be more explanatory

**Comment by Eknir** [comment] 2021-05-21 13:30
This issue is mentioned in https://github.com/ethersphere/bee/issues/1639, and supposed to be fixed by https://github.com/ethersphere/bee/issues/1685 and https://github.com/ethersphere/bee/issues/1685 https://github.com/ethersphere/bee/issues/1653 .

It would be amazing if you can validate if that is indeed the case for v0.6.0. If not, please reopen this issue. If it is fixed, I would also be happy to read it here!

**Closed by Eknir** 2021-05-21 13:30 UTC
Labels: bug, issue
