### ISSUE TITLE
UX improvement: handle is invalid error

### ISSUE THREAD

**Issue by metacertain** [ethersphere/bee#590] opened 2020-08-19 14:06 UTC
# Problem
./dist/bee start
does not seem to work with default values currently, gives an error "Error: The handle is invalid." after showing ASCII bee
Might be a windows related issue

## Acceptance criterea
Restore simple node start to a working state

**Comment by janos** [comment] 2020-08-19 15:53
I was unable to reproduce this on macOS with the current master with commit 58879ea762e436bc630dd19231164f6b20223615. This may indeed be a windows related issue, I will try in a windows virtual machine, also.

**Comment by metacertain** [comment] 2020-08-20 12:42
After a thoughtful retry, the minimum amount of arguments/configuration that makes bee start (on windows) is
./dist/bee start --password "some pass phze"

so it might be a miscommunication of a password error

**Comment by acud** [comment] 2020-10-02 11:45
is this still an issue?

**Comment by Eknir** [comment] 2020-10-13 11:52
@metacertain, could you please verify if this is still an issue? Close the issue if it is solved and put the issue to the backlog if it persists?
Thanks!

**Comment by metacertain** [comment] 2020-10-13 16:55
$ ./dist/bee start

Welcome to the Swarm.... Bzzz Bzzzz Bzzzz
                \     /
            \    o ^ o    /
              \ (     ) /
   ____________(%%%%%%%)____________
  (     /   /  )%%%%%%%(  \   \     )
  (___/___/__/           \__\___\___)
     (     /  /(%%%%%%%)\  \     )
      (__/___/ (%%%%%%%) \___\__)
              /(       )\
            /   (%%%%%)   \
                 (%%%)
                   !
Password:
Error: The handle is invalid.


This is the output when I try to start bee without configuration provided. "The handle is invalid" part means, the password is not provided. This is not really straightforward, let's change this to a better UX

**Comment by Eknir** [comment] 2020-10-26 09:15
Hi @metacertain ,

I am assigning this issue to you, so you can make the PR to improve this ux.

**Comment by Eknir** [comment] 2021-01-28 13:57
@metacertain , I changed the priority of this issue from Low to High. As this is something that is directly affecting user experience.
Could you please take this one upon you and ensure a better user experience here?

**Comment by acud** [comment] 2021-08-10 20:47
since no one can reproduce this and it has not been reported by other users i am closing this issue

**Closed by acud** 2021-08-10 20:47 UTC
Labels: bug
