### ISSUE TITLE
CI fails in retrieval

### ISSUE THREAD

**Issue by jmozah** [ethersphere/bee#725] opened 2020-09-22 12:15 UTC
had this in CI with "instant-chunk-rapair" branch for mac-build

=== RUN   TestDelivery
##[error]    retrieval_test.go:133: unexpected balance on server. want 10 got 0
--- FAIL: TestDelivery (0.00s)

**Comment by acud** [comment] 2020-10-02 11:51
duplicate of https://github.com/ethersphere/bee/issues/721

**Closed by acud** 2020-10-02 11:51 UTC
Labels: flaky-test
