### ISSUE TITLE
It's not clear when the syncing is complete

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#1007] opened 2020-11-23 15:06 UTC
#### Summary
When tracking that status of an upload with the `/tags` endpoint it's not really clear when the data is synced to the network. The documentation doesn't mention this information and upon asking about this I got the information that when 
```
stored == seen + synced
```
However I managed to get a state when `seen+synced` was more than `stored` and yet the data was not available.

```
% curl7 -v http://localhost:1633/tags/3606366987
*   Trying 127.0.0.1:1633...
* Connected to localhost (127.0.0.1) port 1633 (#0)
> GET /tags/3606366987 HTTP/1.1
> Host: localhost:1633
> User-Agent: curl/7.73.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Cache-Control: no-cache, private, max-age=0
< Content-Type: application/json; charset=utf-8
< Date: Mon, 23 Nov 2020 14:29:21 GMT
< Content-Length: 239
< 
{"total":356,"split":356,"seen":343,"stored":356,"sent":31,"synced":15,"uid":3606366987,"name":"unnamed_tag_1606140981","address":"533329fc9c8e674f576aa04037e2be8ea3584cbea024d6f5da6980fc188a178d","startedAt":"2020-11-23T15:16:21+01:00"}
```

**Comment by Eknir** [comment] 2020-12-18 12:39
This is a duplicate of #918 . Thanks for reporting. Let's continue tracking this under #918.

**Closed by Eknir** 2020-12-18 12:39 UTC
Labels: bug, issue
