### ISSUE TITLE
Uploading tarfile to gateway fails inconsistently

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#1001] opened 2020-11-23 11:57 UTC
#### Summary
I tried to upload a tarfile to the gateway nodes and they failed inconsistently.

#### Steps to reproduce
I used this command:

```sh
curl \                                                                                                           
    -X POST -v -D - \
    -H "Content-Type: application/x-tar" \
    -H "Swarm-Index-Document: index.html" \
    -H "Swarm-Error-Document: index.html" \
    --data-binary @/Users/attila/Downloads/website.tar https://gateway.staging.ethswarm.org/dirs
```

The file to be used has 1310720 bytes and can be found here:
https://bee-0.gateway.ethswarm.org/files/6564a495efaff7ffc1bdf5f4f050458e59c96abf8658ba65afdbc06731a6e588

This is the curl output I got when there were an error:
```
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 23.21.75.176...
* TCP_NODELAY set
* Connected to bee-0.gateway.staging.ethswarm.org (23.21.75.176) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.gateway.staging.ethswarm.org
*  start date: Oct 17 07:47:20 2020 GMT
*  expire date: Jan 15 07:47:20 2021 GMT
*  subjectAltName: host "bee-0.gateway.staging.ethswarm.org" matched cert's "*.gateway.staging.ethswarm.org"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7ff1d5000400)
> POST /dirs HTTP/2
> Host: bee-0.gateway.staging.ethswarm.org
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/x-tar
> Swarm-Index-Document: index.html
> Swarm-Error-Document: index.html
> Content-Length: 1310720
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* We are completely uploaded and fine
* HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

I also tried with different gateway nodes (e.g. `https://bee-0.gateway.ethswarm.org/dirs`) and staging nodes as well. The behavior was the same for all. Even if I tried to upload the same file repeatedly to the same node it failed sometimes.

#### Expected behavior
I would expect that the upload either succeeds or fails with a reasonable HTTP error code.

**Comment by zbiljic** [comment] 2020-11-23 13:08
This may be related when `cURL` is using HTTP/2 version. Trying same command with `--http1.1` flag might work.

**Comment by agazso** [comment] 2020-11-23 14:31
Indeed, on macOS the builtin curl command uses HTTP/2 by default and it gives the inconsistent behavior that can be seen in the issue.

When using curl from Homebrew (version 7.73.0) it uses HTTP/1.1 by default and it works as expected.

**Comment by Eknir** [comment] 2020-11-30 17:18
@significance , documentation

**Comment by Eknir** [comment] 2020-12-18 12:43
I would like to confirm:
1) Was this issue indeed created by http/2?
2) Is there nothing we can do about this on our side (@vandot)?

If the issue is not anymore an issue, could you please close it @agazso ?

**Comment by vandot** [comment] 2020-12-21 08:39
@Eknir maybe try to disable HTTP2?
On some other issue where we suspected HTTP2 was an issue but @acud confirmed it was on `bee` side, it is related to downloading big files.

**Comment by Eknir** [comment] 2021-01-28 14:06
@agazso, could you please confirm to me if this is still an issue? If so, I would like to plan a meeting with @vandot and @acud to see if we can nail down the culprit.

**Comment by agazso** [comment] 2021-01-28 14:42
Well, I don't have the issue anymore after upgrading `curl` on macOS (which is using HTTP/1.1 by default). However I don't know if the original problem regarding HTTP/2 has been solved or not.

**Closed** 2021-03-03 08:22 UTC
Labels: bug, issue
