### ISSUE TITLE
New pusher approach incompatible with shallow depth check

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#2727] opened 2021-12-08 18:12 UTC
### Context 
Latest 1.4.1 release on mainnet

### Summary
While working on pushing newly updated OSM tiles into the mainnet, I noticed that checks were being repeatedly issued to one of my peers.  Previous uses of the same uploading approach resulted in no checks as the load was distributed across enough peers to stay within the time settlement limits.

### Expected behavior
Either multiple peers should be receiving checks if I'm pushing too fast or no peers should be receiving checks.  Why just one peer receiving multiple checks?

Note:  I have increased the kademlia limits so that I have 100s of connected peers in the lower numbered bins.  Specifically 619 connected peers across bins 0 (left) through 15 (right):  `228 148 118 60 29 16 9 5 2 1 2 1 0 0 0 0` with a depth of 8.

### Actual behavior
One peer, c2969b57581bdbaac767bdb737b9b5f1201eb16ae9304d4df48dfa51298ed827, is receiving multiple checks.

I've added additional logging to track when credits are being apply by the code.  It reveals that pushPeer is crediting the same peer for the same chunk repeatedly.  This is apparently due to the shallow receipt depth check not counting the push as valid until it has been retried numerous times.  Unfortunately, all of those retries are going to the SAME peer which is apparently the deepest part of the swarm, just not as deep as the pusher node's depth is expecting.

In the previous implementation of the pusher, the entire push queue would be worked off before a shallow depth chunk would be retried.  This gave the swarm a chance to actually change the depth before a shallow chunk was retried.  And even if the depth had not changed, the time delay would prevent slamming traffic against a single peer exceeding the time settlement threshold and causing actual cheques to be issued to peers that are definitely NOT doing what is expected by the pusher.

```
time="2021-12-08T12:46:50-05:00" level=trace msg="pushsync: pushPeer credit.Apply peer c2969b57581bdbaac767bdb737b9b5f1201eb16ae9304d4df48dfa51298ed827 for chunk c380020d0ebcd7277f99188ec3a41a3aef4a8808159573d94e4b24e3064601d4"
time="2021-12-08T12:46:51-05:00" level=trace msg="pusher: cannot push chunk c380020d0ebcd7277f99188ec3a41a3aef4a8808159573d94e4b24e3064601d4: pusher: shallow receipt depth 7, want at least 8"
time="2021-12-08T12:49:24-05:00" level=trace msg="pushsync: pushPeer credit.Apply peer c2969b57581bdbaac767bdb737b9b5f1201eb16ae9304d4df48dfa51298ed827 for chunk c380020d0ebcd7277f99188ec3a41a3aef4a8808159573d94e4b24e3064601d4"
time="2021-12-08T12:49:25-05:00" level=trace msg="pusher: cannot push chunk c380020d0ebcd7277f99188ec3a41a3aef4a8808159573d94e4b24e3064601d4: pusher: shallow receipt depth 7, want at least 8"
time="2021-12-08T12:50:24-05:00" level=trace msg="pushsync: pushPeer credit.Apply peer c2969b57581bdbaac767bdb737b9b5f1201eb16ae9304d4df48dfa51298ed827 for chunk c380020d0ebcd7277f99188ec3a41a3aef4a8808159573d94e4b24e3064601d4"
time="2021-12-08T12:50:25-05:00" level=trace msg="pusher: cannot push chunk c380020d0ebcd7277f99188ec3a41a3aef4a8808159573d94e4b24e3064601d4: pusher: shallow receipt depth 7, want at least 8"
time="2021-12-08T12:51:21-05:00" level=trace msg="pushsync: pushPeer credit.Apply peer c2969b57581bdbaac767bdb737b9b5f1201eb16ae9304d4df48dfa51298ed827 for chunk c380020d0ebcd7277f99188ec3a41a3aef4a8808159573d94e4b24e3064601d4"
time="2021-12-08T12:51:22-05:00" level=trace msg="pusher: cannot push chunk c380020d0ebcd7277f99188ec3a41a3aef4a8808159573d94e4b24e3064601d4: pusher: shallow receipt depth 7, want at least 8"
time="2021-12-08T12:52:18-05:00" level=trace msg="pushsync: pushPeer credit.Apply peer c2969b57581bdbaac767bdb737b9b5f1201eb16ae9304d4df48dfa51298ed827 for chunk c380020d0ebcd7277f99188ec3a41a3aef4a8808159573d94e4b24e3064601d4"
time="2021-12-08T12:52:19-05:00" level=trace msg="pusher: cannot push chunk c380020d0ebcd7277f99188ec3a41a3aef4a8808159573d94e4b24e3064601d4: pusher: shallow receipt depth 7, want at least 8"
time="2021-12-08T12:52:48-05:00" level=trace msg="pushsync: pushPeer credit.Apply peer c2969b57581bdbaac767bdb737b9b5f1201eb16ae9304d4df48dfa51298ed827 for chunk c380020d0ebcd7277f99188ec3a41a3aef4a8808159573d94e4b24e3064601d4"
time="2021-12-08T12:52:49-05:00" level=trace msg="pusher: pushed chunk c380020d0ebcd7277f99188ec3a41a3aef4a8808159573d94e4b24e3064601d4 to node c2969b57581bdbaac767bdb737b9b5f1201eb16ae9304d4df48dfa51298ed827, receipt depth 7"
```
### Steps to reproduce
As with all good things, this would be difficult to reproduce because a pusher node needs to push a chunk into a shallower portion of the swarm than the pusher's own expected depth.  Once that condition is met, you will see the quick push attempts to a single peer of a single chunk interspersed with shallow receipt depth warnings.

### Possible solution
Shallow receipt depth retries should be delayed by some (arbitrary) delay before being retried to allow the swarm connectivity and/or depth to actually change before retrying.  Otherwise, the shallow depth is unlikely to be different on retries that are issued too quickly.

**Comment by ldeffenb** [comment] 2021-12-08 18:20
If you're curious, here's the pusher depth metrics on the current execution of my uploader noder:
```
bee_pusher_receipt_depth{depth="10"} 85348
bee_pusher_receipt_depth{depth="11"} 57537
bee_pusher_receipt_depth{depth="12"} 33522
bee_pusher_receipt_depth{depth="13"} 17568
bee_pusher_receipt_depth{depth="14"} 9006
bee_pusher_receipt_depth{depth="15"} 4601
bee_pusher_receipt_depth{depth="16"} 2226
bee_pusher_receipt_depth{depth="17"} 1149
bee_pusher_receipt_depth{depth="18"} 607
bee_pusher_receipt_depth{depth="19"} 296
bee_pusher_receipt_depth{depth="20"} 153
bee_pusher_receipt_depth{depth="21"} 79
bee_pusher_receipt_depth{depth="22"} 26
bee_pusher_receipt_depth{depth="23"} 16
bee_pusher_receipt_depth{depth="24"} 7
bee_pusher_receipt_depth{depth="25"} 3
bee_pusher_receipt_depth{depth="26"} 2
bee_pusher_receipt_depth{depth="27"} 2
bee_pusher_receipt_depth{depth="28"} 1
bee_pusher_receipt_depth{depth="29"} 2
bee_pusher_receipt_depth{depth="7"} 7084
bee_pusher_receipt_depth{depth="8"} 32141
bee_pusher_receipt_depth{depth="9"} 9398
```

**Comment by acud** [comment] 2021-12-09 18:09
Thanks for the issue report @ldeffenb, however, I'm not sure if I'd go as far as saying that the new pusher approach is incompatible with the shallow receipt check. In fact, it is somewhat intentional.
If you'd have a look in the pushsync protocol implementation, you'll see that there's a skiplist in the protocol to keep track of chunk push attempts (successful or not). This is meant to ensure that subsequent chunk retries get a different route in the address space graph. 

Also important to note, is that the skiplist has a TTL on the entries, which becomes a weakness of the old pusher strategy. The problem is especially so for very large upload queues, that would result in the chunk being retried again only after the entry TTL has expired, which would then in turn _not result_ in the chunk getting a different route. So from the skiplist perspective, actually trying to hammer in a chunk over and over within a short period of time is more likely to result in the chunk being synced correctly.

Also something to keep in mind, is that kademlia depths can have a good degree of variance to them, and some neighborhoods are just shallow period. So the receipt will always be shallow. Having retries for it guarantees that you at least give the protocol a chance to resolve the shallow trace into a deep one, but it is never guaranteed.

Another thing to bear in mind, is that you _never_ know if the next peer has no one to forward to. Or you cannot assume that. It is up to that peer to determine that. So even though you might perceive the retry mechanism on that on specific peer as wasteful, it makes sure that the chunk is synced, and due to the fact that Swarm enforces payments for services, it is safe to assume that service will incur charge, and that is in order to guarantee certain level of service from the network, which is perfectly in order.

**Comment by acud** [comment] 2021-12-20 21:26
should be fixed with https://github.com/ethersphere/bee/pull/2731

**Closed by acud** 2021-12-20 21:26 UTC
Labels: issue, needs-triaging
