### ISSUE TITLE
High CPU Usage. Repeated message is "error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"

### ISSUE THREAD

**Issue by smash0190** [ethersphere/bee#3090] opened 2022-07-17 15:33 UTC
Swarm Bee uses the entire CPU and has repeated entries 
of "error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
in log.

### Context
1.6.2-09106b54

### Summary
The node used to work fine but now takes up the entire CPU and continuously outputs this message:
 "error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"

### Expected behavior
Take up usual CPU usage <1 core.

### Actual behavior
Takes up entire CPU.
Configuration is as described in the manual. Nodes is behind NAT but ports are configured and accessible as well as configure in bee.yaml

```
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
Jul 17 11:32:22 basti-desktop bee[553533]: time="2022-07-17T11:32:22-04:00" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
```

### Steps to reproduce

No software change caused the current behavior.

### Possible solution

Don't know.

**Comment by ldeffenb** [comment] 2022-07-17 17:01
Can you browse to the debug port and access /debug/pprof?  From there, pull the goroutine and heap pages and post them here.  That may show what is causing the lock contention.
http://localhost:1635/debug/pprof/

**Comment by tmm360** [comment] 2022-07-18 15:40
I've the same logs in console. I'm running two nodes 1.6.2, and these are from debug api:
[logs.zip](https://github.com/ethersphere/bee/files/9133313/logs.zip)

**Comment by ronaldverschoor** [comment] 2022-07-18 17:56
Same issue with my nodes

**Comment by ldeffenb** [comment] 2022-07-19 11:44
> we've seen this yesterday and there's already a fix on `master`. we will be snooping around for some more problems later today with the aim of releasing the fix asap

Any hint as to which fix on master fixes this report?

**Comment by acud** [comment] 2022-07-19 12:54
https://github.com/ethersphere/bee/pull/3091

**Comment by tmm360** [comment] 2022-07-19 21:46
@acud running 1.6.3-rc1, but error is still here.

**Comment by jpritikin** [comment] 2022-07-19 22:09
I'm seeing the same behavior with 1.6.2. My node was down for 10 days because my Gnosis Chain endpoint died. I got it going again today and this behavior started.

**Comment by jpritikin** [comment] 2022-07-20 16:29
At least for me, the problem is gone after upgrading to 1.6.3.

**Comment by tmm360** [comment] 2022-07-21 18:21
for me instead is still full of these logs:
```
time="2022-07-21T18:01:41Z" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
time="2022-07-21T18:01:41Z" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
time="2022-07-21T18:01:41Z" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
time="2022-07-21T18:01:41Z" level=error msg="prepare credit: failed to acquire lock: context deadline exceeded: failed to lock"
```

**Comment by acud** [comment] 2022-07-25 11:23
should be fixed with the latest release.

**Closed by acud** 2022-07-25 11:23 UTC
Labels: bug, issue
