### ISSUE TITLE
cashout exeute success but cannot query the record in the goerli.etherscan.io

### ISSUE THREAD

**Issue by buyustudio2** [ethersphere/bee#2084] opened 2021-06-15 00:40 UTC
I sent the post request like  http://localhost:1635/chequebook/cashout/{peer-id},and get the response like {'transactionHash':'0x2c904b92bab87111c4ee93f85c5140733064958144930a21e590aa13f90b28d1'}.
however I paste the Hash to goerli.etherscan.io and it says 'Sorry, We are unable to locate this TxnHash'.
How it happened,what should I do to cashout my cheque?

**Comment by ldeffenb** [comment] 2021-06-15 01:13
First, given the high gas prices, does your Ethereum address have sufficient gETH to pay for a cashout?

And second, like I keep saying on #bee-support: 
The goerli network is severely backlogged and the gas price is high.  All blockchain interactions will be SLOW and may encounter unexpected errors as a result.  Now is NOT a good time to be deploying a new node or trying to cash checks or buying stamps.  https://stats.goerli.net/

**Comment by buyustudio2** [comment] 2021-06-15 01:47
Thank you very much for reply.
I send POST request via POSTMAN program and set the gas_price:200,gas_limit:470000 in the request header ,but it still not work. 
If I do not cash all my cheque out ,will it be too late to cashout in the future?

**Comment by LanugoChen** [comment] 2021-06-15 10:27
I met the same problem. I'm sure I have enough gETH to pay the gas.

**Comment by santakrosbom** [comment] 2021-06-15 11:00
https://github.com/ethersphere/bee/issues/2084#issue-920880331

**Comment by ralph-pichler** [comment] 2021-06-17 08:07
if you encounter this issue and the tx does not appear on etherscan anymore (or ever), use this tool https://github.com/ethersphere/nonce-reset on your datadir (v1.1.0) for bee `>0.6.*`. afterwards redo the cashout post request but make sure to specify a gas price using the `Gas-Price` http header (e.g. `curl -XPOST -H 'Gas-Price: 200000000000' http://localhost:1635/chequebook/cashout/{peer-id}`).

**Comment by LanugoChen** [comment] 2021-06-18 06:01
> if you encounter this issue and the tx does not appear on etherscan anymore (or ever), use this tool https://github.com/ethersphere/nonce-reset on your datadir (version `v1.1.0`) for bee `>0.6.*`. afterwards redo the cashout post request but make sure to specify a gas price using the `Gas-Price` http header (e.g. `curl -XPOST -H 'Gas-Price: 200000000000' http://localhost:1635/chequebook/cashout/{peer-id}`).

It worked，Thank you！！！

**Comment by acud** [comment] 2021-08-12 15:04
duplicate of https://github.com/ethersphere/bee/issues/1802

**Closed by acud** 2021-08-12 15:04 UTC
Labels: issue
