### ISSUE TITLE
Don't hang api requests waiting for tx generating a Batch of Stamps

### ISSUE THREAD

**Issue by tmm360** [ethersphere/bee#1922] opened 2021-05-31 00:56 UTC
#### Summary
API should reply to clients as quickly as possible. They should never wait a long process before reply, this for different reasons:

- Client must be able to perform other actions in the meantime
- Long requests can have unpredictable time of execution. If the api doesn't reply a task reference, client can't have any information on task state
- Often http clients implement requests timeout. If a task require too long time, the request fails

Currently operation of creating a batch of stamps tries to reply directly the batch id, but this is generated by a transaction that is a very long task to wait.

#### Expected behavior
Stamp generating request should reply a tx Id, or some kind of reference. Another request should be able to reply the batch id when the transaction has been completed.

#### Actual behavior
The api request hang clients for a response until task is completed.

**Comment by ralph-pichler** [comment] 2021-06-04 12:21
duplicate of #1158

**Closed** 2021-06-04 12:42 UTC
Labels: bug, issue
