### ISSUE TITLE
feature request: `bee start` should start a new ultralight node without any further configuration

### ISSUE THREAD

**Issue by significance** [ethersphere/bee#4032] opened 2023-04-25 13:00 UTC
#### Summary
it would be great for user experience if `bee start` started up an ultralight node without any further config.

this simply the following default options 

```
swap-enable: false
debug-api-enable:true
debug-api-addr: 127.0.0.1:1635
```

the debug api is set to be functioning, but only bound to localhost, preventing outside connections.

**Comment by rampall** [comment] 2023-05-05 10:50
tangentially related #3756

**Comment by quinton11** [comment] 2023-05-15 13:15
will love to pick this up if its still open

**Comment by mrekucci** [comment] 2023-09-20 11:58
Duplicate of #4114

**Closed by mrekucci** 2023-09-20 11:58 UTC
Labels: issue
