### ISSUE TITLE
variable TTL for retrieve requests

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#1081] opened 2021-01-05 08:37 UTC
## Background
Retrieve requests have a constant, rigid timeout, after which a different peer is retried to fetch the chunk.
This approach has several weaknesses:
- due to the fact that TTLs are constant and that RTT is always > 0, an upstream peer will necessarily time out on a retrieve request cascade before the downstream peers will.
- it does not make use of the fact that retrieve requests are cheaper within the nearest neighborhood, i.e. as we get closer to the chunk, retrieve requests get cheaper. hence, it would be expected that forwarding nodes closer to the chunk can requests more nodes with a lower price tag, in order to ensure further reliability of QoS.

## Task
In order to improve retrieve request performance and resilience, implement a variable request TTL that uses a curve that decreases the timeout as proximity order increases.
The actual approximation function is at the discretion of the implementer, however certain min/max TTL thresholds should be established and adjustable from within the package.
The curve values between proximity orders should take into account RTT.

## Acceptance criterea
Retrieve request should be retried faster when getting nearer to the chunk.

**Comment by Eknir** [comment] 2021-04-06 10:59
Duplicate of #1044

**Closed by Eknir** 2021-04-06 10:59 UTC
Labels: enhancement, issue
