### ISSUE TITLE
panic: runtime error: index out of range [16] with length 16

### ISSUE THREAD

**Issue by wangxujun163163** [ethersphere/bee#1827] opened 2021-05-21 23:18 UTC
#### Summary
TRAC[2021-05-22T07:16:51+08:00] connecting to bootnode /ip4/52.3.228.231/tcp/31304/p2p/16Uiu2HAm92e7bG36gTuUFVrxWrhbsmQP14irjokxc95QNmA48TnG 
panic: runtime error: index out of range [16] with length 16

goroutine 204 [running]:
github.com/ethersphere/bee/pkg/puller.(*Puller).recalcPeer(0xc0001dc0f0, 0x172d398, 0xc00120bdc0, 0xc0002c7f40, 0x20, 0x20, 0x1)
        github.com/ethersphere/bee/pkg/puller/puller.go:220 +0x67d
github.com/ethersphere/bee/pkg/puller.(*Puller).manage(0xc0001dc0f0)
        github.com/ethersphere/bee/pkg/puller/puller.go:170 +0x428
created by github.com/ethersphere/bee/pkg/puller.New
        github.com/ethersphere/bee/pkg/puller/puller.go:82 +0x2aa

**Comment by maginaro** [comment] 2021-05-22 08:41
same to me..

**Comment by addicted0010** [comment] 2021-05-22 08:57
same here..

**Comment by cppfuns** [comment] 2021-05-22 11:53
Unfortunately the same result

**Comment by ldeffenb** [comment] 2021-05-22 13:22
Duplicate of #1823

**Comment by addicted0010** [comment] 2021-05-23 07:15
Well, my issue has been solved once upgraded to bee-clef v0.4.12 and bee v0.6.1.
Hope this helps.

**Comment by ldeffenb** [comment] 2021-05-23 11:15
> Well, my issue has been solved once upgraded to bee-clef v0.4.12 and bee v0.6.1.
> Hope this helps.

Actually, you're just lucky.  The [16] error seems to be caused by the peer that you are syncing with, not your own node.  If you don't connect to the "bad" peer, you won't die.  But it could be just a matter of time...

**Comment by addicted0010** [comment] 2021-05-23 12:43
> > Well, my issue has been solved once upgraded to bee-clef v0.4.12 and bee v0.6.1.
> > Hope this helps.
> 
> Actually, you're just lucky. The [16] error seems to be caused by the peer that you are syncing with, not your own node. If you don't connect to the "bad" peer, you won't die. But it could be just a matter of time...

Thanks for explanation. I will wait for v0.6.2 then.

**Comment by Eknir** [comment] 2021-05-31 16:42
Hi all,
This is addressed with the latest pre-release. Please update your nodes. If the issue still persists, I would appreciate that you reply on this issue and I will reopen it. If it is fixed, a comment is also appreciated!

**Closed by Eknir** 2021-05-31 16:42 UTC
Labels: bug, issue

**Comment by ldeffenb** [comment] 2021-05-31 18:34
I have been running the pre-pre-release  0.6.2 from master for 4 days now and have not seen any instances of this issue once this fix was pushed into master.  And prior to that, I had 3 nodes that couldn't stay up for more than an hour or so without encountering it.  So I'd consider it fixed.
